# GVH Diagonal Cubic 0.2.23.4.1 — Timelike Field Model Selection and Falsifiability — Traceability Fix

**Auteur : Charlemagne O Laurince**

## Objectif

Comparer trois interprétations de \(u^\mu\) sans transformer un classement technique en sélection physique :

\[
u^\mu=u^\mu_{\rm matter},
\]

\[
u_\mu=-\frac{\nabla_\mu\phi}
{\sqrt{-\nabla_\alpha\phi\nabla^\alpha\phi}},
\]

ou un champ vectoriel unitaire indépendant.

Le notebook doit conclure soit à une sélection unique par les postulats GVH, soit à la nécessité d'un nouveau postulat falsifiable.

## Statuts

```text
PASS-UNIQUE-TIMELIKE-MODEL-SELECTED
PASS-MODEL-CLASSIFICATION-NO-UNIQUE-SELECTION
BLOCKED-NO-UNIQUE-MODEL-FROM-CURRENT-POSTULATES
NEW-FALSIFIABLE-POSTULATE-REQUIRED
```

---

## Correction 0.2.23.4.1

Cette version met à jour la dépendance canonique :

```text
0.2.23.3
```

vers :

```text
0.2.23.3.1
```

La logique scientifique, les calculs et le verdict restent inchangés.

In [1]:
from __future__ import annotations
import json, subprocess, sys
from datetime import datetime, timezone
from pathlib import Path
import numpy as np
import pandas as pd

pd.set_option("display.max_columns", 180)
pd.set_option("display.max_colwidth", 240)
print("Python :", sys.version)

Python : 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

# 1. Dépôt et chemins

In [2]:
REPOSITORY_URL = "https://github.com/col38470682/Univers.git"
REPOSITORY_DIR = Path("/content/Univers")
PROJECT_ROOT = REPOSITORY_DIR / "gvh_diagonal_cubic"

if (REPOSITORY_DIR / ".git").exists():
    subprocess.run(
        ["git", "-C", str(REPOSITORY_DIR), "pull", "--ff-only"],
        check=True,
    )
else:
    subprocess.run(
        ["git", "clone", REPOSITORY_URL, str(REPOSITORY_DIR)],
        check=True,
    )

if not PROJECT_ROOT.exists():
    raise FileNotFoundError(PROJECT_ROOT)

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed" / "timelike_field"
EXPORT_DIR = PROJECT_ROOT / "exports"

for directory in [PROCESSED_DIR, EXPORT_DIR]:
    directory.mkdir(parents=True, exist_ok=True)

print("PROJECT_ROOT :", PROJECT_ROOT)

PROJECT_ROOT : /content/Univers/gvh_diagonal_cubic

# 2. Dépendances

In [3]:
NOTEBOOK_PATTERNS = {
    "0.2.21": "*0.2.21*Equivalence*Principle*PPN*Constraints*.ipynb",
    "0.2.22": "*0.2.22*Static*Spherical*PPN*Derivation*.ipynb",
    "0.2.23": "*0.2.23*Covariant*Static*Field*Source*Matching*.ipynb",
    "0.2.23.1": "*0.2.23.1*Weak*Field*Coefficient*Extraction*PPN*.ipynb",
    "0.2.23.2": "*0.2.23.2*Covariant*Source*Projector*Derivation*.ipynb",
    "0.2.23.3.1": "*0.2.23.3.1*Timelike*Field*Dynamics*Covariant*Closure*.ipynb",
}

resolved = {}
for notebook_id, pattern in NOTEBOOK_PATTERNS.items():
    matches = sorted(PROJECT_ROOT.rglob(pattern))
    resolved[notebook_id] = matches[0] if matches else None

source_notebooks_df = pd.DataFrame([
    {
        "notebook_id": key,
        "resolved_path": str(value) if value else "",
        "found": value is not None,
    }
    for key, value in resolved.items()
])

all_sources_found = bool(source_notebooks_df["found"].all())
source_notebooks_df

,notebook_id,resolved_path,found
0,0.2.21,/content/Univers/gvh_diagonal_cubic/0.2_gravity/0.2B_astrophysics_validation/GVH_Diagonal_Cubic_0.2.21_Equivalence_Principle_PPN_Constraints.ipynb,True
1,0.2.22,/content/Univers/gvh_diagonal_cubic/0.2_gravity/0.2B_astrophysics_validation/GVH_Diagonal_Cubic_0.2.22_Static_Spherical_Solution_PPN_Derivation.ipynb,True
2,0.2.23,/content/Univers/gvh_diagonal_cubic/0.2_gravity/0.2B_astrophysics_validation/GVH_Diagonal_Cubic_0.2.23_Covariant_Static_Field_Equations_Source_Matching.ipynb,True
3,0.2.23.1,/content/Univers/gvh_diagonal_cubic/0.2_gravity/0.2B_astrophysics_validation/GVH_Diagonal_Cubic_0.2.23.1_Weak_Field_Coefficient_Extraction_for_PPN_UPDATED.ipynb,True
4,0.2.23.2,/content/Univers/gvh_diagonal_cubic/0.2_gravity/0.2B_astrophysics_validation/GVH_Diagonal_Cubic_0.2.23.2_Covariant_Source_Projector_Derivation.ipynb,True
5,0.2.23.3.1,/content/Univers/gvh_diagonal_cubic/0.2_gravity/0.2B_astrophysics_validation/GVH_Diagonal_Cubic_0.2.23.3.1_Timelike_Field_Dynamics_and_Covariant_Closure_Dependency_Detection_Fix.ipynb,True

# Audit de la dépendance 0.2.23.3.1

In [4]:
dependency_02331_df = source_notebooks_df.loc[
    source_notebooks_df[
        "notebook_id"
    ] == "0.2.23.3.1"
].copy()

dependency_02331_pass = bool(
    not dependency_02331_df.empty
    and dependency_02331_df[
        "found"
    ].all()
)

print(
    "Dépendance 0.2.23.3.1 trouvée :",
    dependency_02331_pass,
)

dependency_02331_df

Dépendance 0.2.23.3.1 trouvée : True

,notebook_id,resolved_path,found
5,0.2.23.3.1,/content/Univers/gvh_diagonal_cubic/0.2_gravity/0.2B_astrophysics_validation/GVH_Diagonal_Cubic_0.2.23.3.1_Timelike_Field_Dynamics_and_Covariant_Closure_Dependency_Detection_Fix.ipynb,True

# 3. Modèles candidats

In [5]:
models_df = pd.DataFrame([
    {
        "model_id": "MATTER_COMOVING",
        "name": "Matter four-velocity",
        "definition": "u^mu = u^mu_matter",
        "new_dof": 0,
        "vacuum_defined": False,
        "multi_fluid_unique": False,
        "selected_by_current_GVH": False,
    },
    {
        "model_id": "SCALAR_GRADIENT",
        "name": "Normalized scalar gradient",
        "definition": "u_mu = -grad_mu(phi)/sqrt(-grad(phi)^2)",
        "new_dof": 1,
        "vacuum_defined": True,
        "multi_fluid_unique": True,
        "selected_by_current_GVH": False,
    },
    {
        "model_id": "INDEPENDENT_VECTOR",
        "name": "Independent unit timelike vector",
        "definition": "u^mu independent with u^2=-1",
        "new_dof": 3,
        "vacuum_defined": True,
        "multi_fluid_unique": True,
        "selected_by_current_GVH": False,
    },
])
models_df

,model_id,name,definition,new_dof,vacuum_defined,multi_fluid_unique,selected_by_current_GVH
0,MATTER_COMOVING,Matter four-velocity,u^mu = u^mu_matter,0,False,False,False
1,SCALAR_GRADIENT,Normalized scalar gradient,u_mu = -grad_mu(phi)/sqrt(-grad(phi)^2),1,True,True,False
2,INDEPENDENT_VECTOR,Independent unit timelike vector,u^mu independent with u^2=-1,3,True,True,False

# 4. Critères

In [6]:
criteria_df = pd.DataFrame([
    ("C1", "Defined in vacuum", 2.0, True),
    ("C2", "Manifest covariance", 2.0, True),
    ("C3", "Minimal new degrees of freedom", 1.0, False),
    ("C4", "Unique in multi-fluid systems", 1.5, False),
    ("C5", "Compatible with Pi_mn[T]", 2.0, True),
    ("C6", "Global exterior solution possible", 2.0, True),
    ("C7", "GR limit identifiable", 2.0, True),
    ("C8", "Preferred-frame sector controllable", 1.5, False),
    ("C9", "Can generate alpha_t and alpha_s", 2.0, True),
    ("C10", "Independent falsifiable prediction", 2.0, True),
    ("C11", "Selected by existing GVH postulates", 3.0, True),
], columns=["criterion_id", "criterion", "weight", "hard_gate"])
criteria_df

   criterion_id                            criterion  weight  hard_gate
0            C1                    Defined in vacuum     2.0       True
1            C2                  Manifest covariance     2.0       True
2            C3       Minimal new degrees of freedom     1.0      False
3            C4        Unique in multi-fluid systems     1.5      False
4            C5             Compatible with Pi_mn[T]     2.0       True
5            C6    Global exterior solution possible     2.0       True
6            C7                GR limit identifiable     2.0       True
7            C8  Preferred-frame sector controllable     1.5      False
8            C9     Can generate alpha_t and alpha_s     2.0       True
9           C10   Independent falsifiable prediction     2.0       True
10          C11  Selected by existing GVH postulates     3.0       True

# 5. Matrice d'évaluation transparente

In [7]:
rows = [
    ("MATTER_COMOVING","C1",0.0,"Not defined in vacuum"),
    ("MATTER_COMOVING","C2",1.0,"Covariant where matter flow exists"),
    ("MATTER_COMOVING","C3",1.0,"No new independent field"),
    ("MATTER_COMOVING","C4",0.0,"Ambiguous for non-comoving fluids"),
    ("MATTER_COMOVING","C5",1.0,"Defines local spatial projector"),
    ("MATTER_COMOVING","C6",0.0,"No unique vacuum exterior"),
    ("MATTER_COMOVING","C7",1.0,"GR limit straightforward"),
    ("MATTER_COMOVING","C8",0.7,"Matter-frame dependence"),
    ("MATTER_COMOVING","C9",0.3,"Global response incomplete"),
    ("MATTER_COMOVING","C10",0.3,"Weak clean-vacuum falsifiability"),
    ("MATTER_COMOVING","C11",0.0,"Not selected by current GVH"),

    ("SCALAR_GRADIENT","C1",1.0,"Defined if scalar gradient is timelike"),
    ("SCALAR_GRADIENT","C2",1.0,"Manifestly covariant"),
    ("SCALAR_GRADIENT","C3",0.7,"Adds one scalar"),
    ("SCALAR_GRADIENT","C4",1.0,"Unique once phi is fixed"),
    ("SCALAR_GRADIENT","C5",1.0,"Defines h_mn and Pi_mn"),
    ("SCALAR_GRADIENT","C6",1.0,"Global exterior possible"),
    ("SCALAR_GRADIENT","C7",0.8,"GR limit requires decoupling"),
    ("SCALAR_GRADIENT","C8",0.6,"Foliation effects remain"),
    ("SCALAR_GRADIENT","C9",0.8,"Metric response after action is fixed"),
    ("SCALAR_GRADIENT","C10",0.8,"Scalar-clock signatures possible"),
    ("SCALAR_GRADIENT","C11",0.0,"No scalar-clock postulate in current GVH"),

    ("INDEPENDENT_VECTOR","C1",1.0,"Defined in vacuum"),
    ("INDEPENDENT_VECTOR","C2",1.0,"Manifestly covariant"),
    ("INDEPENDENT_VECTOR","C3",0.3,"Adds vector modes"),
    ("INDEPENDENT_VECTOR","C4",1.0,"Independent of matter fluids"),
    ("INDEPENDENT_VECTOR","C5",1.0,"Defines h_mn and Pi_mn"),
    ("INDEPENDENT_VECTOR","C6",1.0,"Global exterior possible"),
    ("INDEPENDENT_VECTOR","C7",0.8,"GR limit requires decoupling"),
    ("INDEPENDENT_VECTOR","C8",0.3,"Strong preferred-frame risk"),
    ("INDEPENDENT_VECTOR","C9",1.0,"Can generate metric response"),
    ("INDEPENDENT_VECTOR","C10",1.0,"Preferred-frame and wave tests"),
    ("INDEPENDENT_VECTOR","C11",0.0,"No vector action in current GVH"),
]

evaluation_df = pd.DataFrame(
    rows,
    columns=["model_id","criterion_id","score","justification"],
).merge(criteria_df, on="criterion_id").merge(
    models_df[["model_id","name"]],
    on="model_id",
)

evaluation_df["weighted_score"] = (
    evaluation_df["score"] * evaluation_df["weight"]
)
evaluation_df

,model_id,criterion_id,score,justification,criterion,weight,hard_gate,name,weighted_score
0,MATTER_COMOVING,C1,0.0,Not defined in vacuum,Defined in vacuum,2.0,True,Matter four-velocity,0.00
1,MATTER_COMOVING,C2,1.0,Covariant where matter flow exists,Manifest covariance,2.0,True,Matter four-velocity,2.00
2,MATTER_COMOVING,C3,1.0,No new independent field,Minimal new degrees of freedom,1.0,False,Matter four-velocity,1.00
3,MATTER_COMOVING,C4,0.0,Ambiguous for non-comoving fluids,Unique in multi-fluid systems,1.5,False,Matter four-velocity,0.00
4,MATTER_COMOVING,C5,1.0,Defines local spatial projector,Compatible with Pi_mn[T],2.0,True,Matter four-velocity,2.00
5,MATTER_COMOVING,C6,0.0,No unique vacuum exterior,Global exterior solution possible,2.0,True,Matter four-velocity,0.00
6,MATTER_COMOVING,C7,1.0,GR limit straightforward,GR limit identifiable,2.0,True,Matter four-velocity,2.00
7,MATTER_COMOVING,C8,0.7,Matter-frame dependence,Preferred-frame sector controllable,1.5,False,Matter four-velocity,1.05
8,MATTER_COMOVING,C9,0.3,Global response incomplete,Can generate alpha_t and alpha_s,2.0,True,Matter four-velocity,0.60
9,MATTER_COMOVING,C10,0.3,Weak clean-vacuum falsifiability,Independent falsifiable prediction,2.0,True,Matter four-velocity,0.60
10,MATTER_COMOVING,C11,0.0,Not selected by current GVH,Selected by existing GVH postulates,3.0,True,Matter four-velocity,0.00
11,SCALAR_GRADIENT,C1,1.0,Defined if scalar gradient is timelike,Defined in vacuum,2.0,True,Normalized scalar gradient,2.00
12,SCALAR_GRADIENT,C2,1.0,Manifestly covariant,Manifest covariance,2.0,True,Normalized scalar gradient,2.00
13,SCALAR_GRADIENT,C3,0.7,Adds one scalar,Minimal new degrees of freedom,1.0,False,Normalized scalar gradient,0.70
14,SCALAR_GRADIENT,C4,1.0,Unique once phi is fixed,Unique in multi-fluid systems,1.5,False,Normalized scalar gradient,1.50
15,SCALAR_GRADIENT,C5,1.0,Defines h_mn and Pi_mn,Compatible with Pi_mn[T],2.0,True,Normalized scalar gradient,2.00
16,SCALAR_GRADIENT,C6,1.0,Global exterior possible,Global exterior solution possible,2.0,True,Normalized scalar gradient,2.00
17,SCALAR_GRADIENT,C7,0.8,GR limit requires decoupling,GR limit identifiable,2.0,True,Normalized scalar gradient,1.60
18,SCALAR_GRADIENT,C8,0.6,Foliation effects remain,Preferred-frame sector controllable,1.5,False,Normalized scalar gradient,0.90
19,SCALAR_GRADIENT,C9,0.8,Metric response after action is fixed,Can generate alpha_t and alpha_s,2.0,True,Normalized scalar gradient,1.60
20,SCALAR_GRADIENT,C10,0.8,Scalar-clock signatures possible,Independent falsifiable prediction,2.0,True,Normalized scalar gradient,1.60
21,SCALAR_GRADIENT,C11,0.0,No scalar-clock postulate in current GVH,Selected by existing GVH postulates,3.0,True,Normalized scalar gradient,0.00
22,INDEPENDENT_VECTOR,C1,1.0,Defined in vacuum,Defined in vacuum,2.0,True,Independent unit timelike vector,2.00
23,INDEPENDENT_VECTOR,C2,1.0,Manifestly covariant,Manifest covariance,2.0,True,Independent unit timelike vector,2.00
24,INDEPENDENT_VECTOR,C3,0.3,Adds vector modes,Minimal new degrees of freedom,1.0,False,Independent unit timelike vector,0.30
25,INDEPENDENT_VECTOR,C4,1.0,Independent of matter fluids,Unique in multi-fluid systems,1.5,False,Independent unit timelike vector,1.50
26,INDEPENDENT_VECTOR,C5,1.0,Defines h_mn and Pi_mn,Compatible with Pi_mn[T],2.0,True,Independent unit timelike vector,2.00
27,INDEPENDENT_VECTOR,C6,1.0,Global exterior possible,Global exterior solution possible,2.0,True,Independent unit timelike vector,2.00
28,INDEPENDENT_VECTOR,C7,0.8,GR limit requires decoupling,GR limit identifiable,2.0,True,Independent unit timelike vector,1.60
29,INDEPENDENT_VECTOR,C8,0.3,Strong preferred-frame risk,Preferred-frame sector controllable,1.5,False,Independent unit timelike vector,0.45
30,INDEPENDENT_VECTOR,C9,1.0,Can generate metric response,Can generate alpha_t and alpha_s,2.0,True,Independent unit timelike vector,2.00
31,INDEPENDENT_VECTOR,C10,1.0,Preferred-frame and wave tests,Independent falsifiable prediction,2.0,True,Independent unit timelike vector,2.00
32,INDEPENDENT_VECTOR,C11,0.0,No vector action in current GVH,Selected by existing GVH postulates,3.0,True,Independent unit timelike vector,0.00

# 6. Classement technique

In [8]:
score_summary_df = (
    evaluation_df
    .groupby(["model_id","name"], as_index=False)
    .agg(
        weighted_score=("weighted_score","sum"),
        total_weight=("weight","sum"),
    )
)

score_summary_df["normalized_score"] = (
    score_summary_df["weighted_score"]
    / score_summary_df["total_weight"]
)

score_summary_df = (
    score_summary_df
    .sort_values("normalized_score", ascending=False)
    .reset_index(drop=True)
)

score_summary_df["rank"] = np.arange(len(score_summary_df)) + 1
score_summary_df

,model_id,name,weighted_score,total_weight,normalized_score,rank
0,SCALAR_GRADIENT,Normalized scalar gradient,15.90,21.0,0.757143,1
1,INDEPENDENT_VECTOR,Independent unit timelike vector,15.85,21.0,0.754762,2
2,MATTER_COMOVING,Matter four-velocity,9.25,21.0,0.440476,3

# 7. Portes dures

In [9]:
HARD_GATE_THRESHOLD = 0.75

hard_gate_detail_df = evaluation_df.loc[
    evaluation_df["hard_gate"]
].copy()

hard_gate_detail_df["hard_gate_pass"] = (
    hard_gate_detail_df["score"] >= HARD_GATE_THRESHOLD
)

hard_gate_summary_df = (
    hard_gate_detail_df
    .groupby(["model_id","name"], as_index=False)
    .agg(
        hard_gates_passed=("hard_gate_pass","sum"),
        hard_gate_count=("hard_gate_pass","count"),
        all_hard_gates_pass=("hard_gate_pass","all"),
    )
)

hard_gate_summary_df

,model_id,name,hard_gates_passed,hard_gate_count,all_hard_gates_pass
0,INDEPENDENT_VECTOR,Independent unit timelike vector,7,8,False
1,MATTER_COMOVING,Matter four-velocity,3,8,False
2,SCALAR_GRADIENT,Normalized scalar gradient,7,8,False

# 8. Sélection par les postulats GVH

In [10]:
gvh_selection_df = evaluation_df.loc[
    evaluation_df["criterion_id"] == "C11",
    ["model_id","name","score","justification"],
].copy()

selected_models = gvh_selection_df.loc[
    gvh_selection_df["score"] >= 1.0,
    "model_id",
].tolist()

unique_selection_pass = len(selected_models) == 1
gvh_selection_df

,model_id,name,score,justification
10,MATTER_COMOVING,Matter four-velocity,0.0,Not selected by current GVH
21,SCALAR_GRADIENT,Normalized scalar gradient,0.0,No scalar-clock postulate in current GVH
32,INDEPENDENT_VECTOR,Independent unit timelike vector,0.0,No vector action in current GVH

Un score technique supérieur ne constitue pas une sélection physique.

Le critère décisif reste :

\[
\boxed{
\text{le modèle doit découler des postulats GVH}
}
\]

avant toute dérivation de coefficients ou confrontation aux observations.

# 9. Falsifiabilité

In [11]:
falsifiability_df = pd.DataFrame([
    {
        "model_id": "MATTER_COMOVING",
        "prediction": "Directional effects track local matter flow",
        "clean_vacuum_prediction": False,
        "future_tests": "environment dependence",
        "status": "WEAK WITHOUT VACUUM EXTENSION",
    },
    {
        "model_id": "SCALAR_GRADIENT",
        "prediction": "Hypersurface-orthogonal timelike direction",
        "clean_vacuum_prediction": True,
        "future_tests": "scalar clock and foliation signatures",
        "status": "FALSIFIABLE AFTER ACTION FIXED",
    },
    {
        "model_id": "INDEPENDENT_VECTOR",
        "prediction": "Independent vector modes",
        "clean_vacuum_prediction": True,
        "future_tests": "preferred-frame PPN and wave speeds",
        "status": "STRONGLY FALSIFIABLE AFTER COEFFICIENTS FIXED",
    },
])
falsifiability_df

,model_id,prediction,clean_vacuum_prediction,future_tests,status
0,MATTER_COMOVING,Directional effects track local matter flow,False,environment dependence,WEAK WITHOUT VACUUM EXTENSION
1,SCALAR_GRADIENT,Hypersurface-orthogonal timelike direction,True,scalar clock and foliation signatures,FALSIFIABLE AFTER ACTION FIXED
2,INDEPENDENT_VECTOR,Independent vector modes,True,preferred-frame PPN and wave speeds,STRONGLY FALSIFIABLE AFTER COEFFICIENTS FIXED

# 10. Charge paramétrique

In [12]:
parameter_burden_df = pd.DataFrame([
    {
        "model_id": "MATTER_COMOVING",
        "new_field_dof": 0,
        "new_kinetic_coefficients": 0,
        "risk": "source dependence",
    },
    {
        "model_id": "SCALAR_GRADIENT",
        "new_field_dof": 1,
        "new_kinetic_coefficients": "at least one scalar sector",
        "risk": "medium",
    },
    {
        "model_id": "INDEPENDENT_VECTOR",
        "new_field_dof": 3,
        "new_kinetic_coefficients": 4,
        "risk": "high and preferred-frame sensitive",
    },
])
parameter_burden_df

,model_id,new_field_dof,new_kinetic_coefficients,risk
0,MATTER_COMOVING,0,0,source dependence
1,SCALAR_GRADIENT,1,at least one scalar sector,medium
2,INDEPENDENT_VECTOR,3,4,high and preferred-frame sensitive

# 11. Dégénérescence avec GR

In [13]:
gr_limit_df = pd.DataFrame([
    {
        "model_id": "MATTER_COMOVING",
        "GR_limit": "Pi_mn[T]=0 or lambda_T=0",
        "distinct_effect_requires": "anisotropic matter and backreaction",
    },
    {
        "model_id": "SCALAR_GRADIENT",
        "GR_limit": "scalar decouples or is constant",
        "distinct_effect_requires": "nontrivial scalar gradient and fixed action",
    },
    {
        "model_id": "INDEPENDENT_VECTOR",
        "GR_limit": "vector coefficients vanish",
        "distinct_effect_requires": "nonzero coefficients within PPN bounds",
    },
])
gr_limit_df

,model_id,GR_limit,distinct_effect_requires
0,MATTER_COMOVING,Pi_mn[T]=0 or lambda_T=0,anisotropic matter and backreaction
1,SCALAR_GRADIENT,scalar decouples or is constant,nontrivial scalar gradient and fixed action
2,INDEPENDENT_VECTOR,vector coefficients vanish,nonzero coefficients within PPN bounds

# 12. Postulats candidats — non adoptés

In [14]:
candidate_postulates_df = pd.DataFrame([
    {
        "postulate_id": "P-U1",
        "statement": (
            "u_mu is the normalized gradient of a scalar GVH clock field"
        ),
        "selects_model": "SCALAR_GRADIENT",
        "falsifiable_consequence": (
            "hypersurface orthogonality and scalar-foliation effects"
        ),
        "accepted": False,
    },
    {
        "postulate_id": "P-U2",
        "statement": (
            "u^mu is an independent unit vector with a fixed GVH action"
        ),
        "selects_model": "INDEPENDENT_VECTOR",
        "falsifiable_consequence": (
            "preferred-frame PPN parameters and extra modes"
        ),
        "accepted": False,
    },
    {
        "postulate_id": "P-U3",
        "statement": (
            "u^mu follows the dominant matter congruence"
        ),
        "selects_model": "MATTER_COMOVING",
        "falsifiable_consequence": (
            "environment-dependent directional effects"
        ),
        "accepted": False,
    },
])
candidate_postulates_df

,postulate_id,statement,selects_model,falsifiable_consequence,accepted
0,P-U1,u_mu is the normalized gradient of a scalar GVH clock field,SCALAR_GRADIENT,hypersurface orthogonality and scalar-foliation effects,False
1,P-U2,u^mu is an independent unit vector with a fixed GVH action,INDEPENDENT_VECTOR,preferred-frame PPN parameters and extra modes,False
2,P-U3,u^mu follows the dominant matter congruence,MATTER_COMOVING,environment-dependent directional effects,False

# 13. Conditions d'acceptation d'un futur postulat

In [15]:
acceptance_criteria_df = pd.DataFrame([
    {"criterion":"Explicit physical principle","required":True},
    {"criterion":"Unique action or coefficient relations","required":True},
    {"criterion":"Stable linearized dynamics","required":True},
    {"criterion":"Recoverable GR limit","required":True},
    {"criterion":"At least one new falsifiable prediction","required":True},
    {
        "criterion":"No parameter values imported from observational fits",
        "required":True,
    },
])
acceptance_criteria_df

                                              criterion  required
0                           Explicit physical principle      True
1                Unique action or coefficient relations      True
2                            Stable linearized dynamics      True
3                                  Recoverable GR limit      True
4               At least one new falsifiable prediction      True
5  No parameter values imported from observational fits      True

# 14. Décision

In [16]:
classification_pass = bool(
    len(models_df) == 3
    and len(criteria_df) == 11
    and not evaluation_df.empty
)

technical_best_model = str(
    score_summary_df.iloc[0]["model_id"]
)

NEW_POSTULATE_REQUIRED = not unique_selection_pass

if not classification_pass:
    FINAL_STATUS = "BLOCKED-MODEL-CLASSIFICATION"
elif unique_selection_pass:
    FINAL_STATUS = "PASS-UNIQUE-TIMELIKE-MODEL-SELECTED"
else:
    FINAL_STATUS = (
        "PASS-MODEL-CLASSIFICATION-NO-UNIQUE-SELECTION_"
        "BLOCKED-NO-UNIQUE-MODEL-FROM-CURRENT-POSTULATES_"
        "NEW-FALSIFIABLE-POSTULATE-REQUIRED"
    )

decision_df = pd.DataFrame([{
    "final_status": FINAL_STATUS,
    "classification_pass": classification_pass,
    "technical_best_model": technical_best_model,
    "unique_selection_pass": unique_selection_pass,
    "physically_selected_model": (
        selected_models[0] if unique_selection_pass else ""
    ),
    "new_postulate_required": NEW_POSTULATE_REQUIRED,
}])

print("STATUT FINAL :", FINAL_STATUS)
decision_df

STATUT FINAL : PASS-MODEL-CLASSIFICATION-NO-UNIQUE-SELECTION_BLOCKED-NO-UNIQUE-MODEL-FROM-CURRENT-POSTULATES_NEW-FALSIFIABLE-POSTULATE-REQUIRED

,final_status,classification_pass,technical_best_model,unique_selection_pass,physically_selected_model,new_postulate_required
0,PASS-MODEL-CLASSIFICATION-NO-UNIQUE-SELECTION_BLOCKED-NO-UNIQUE-MODEL-FROM-CURRENT-POSTULATES_NEW-FALSIFIABLE-POSTULATE-REQUIRED,True,SCALAR_GRADIENT,False,,True

# 15. Artefact de décision

In [17]:
decision_artifact = {
    "artifact_status": (
        "MODEL_CLASSIFICATION_COMPLETE_"
        "UNIQUE_SELECTION_BLOCKED"
    ),
    "technical_best_model": technical_best_model,
    "technical_ranking_is_physical_selection": False,
    "selected_by_current_GVH_postulates": (
        selected_models[0] if unique_selection_pass else None
    ),
    "new_postulate_required": NEW_POSTULATE_REQUIRED,
    "candidate_postulates": [
        "P-U1 scalar-clock gradient",
        "P-U2 independent unit vector",
        "P-U3 matter congruence",
    ],
    "acceptance_requirements": acceptance_criteria_df[
        "criterion"
    ].tolist(),
    "source_notebooks": list(NOTEBOOK_PATTERNS),
}
decision_artifact

{'artifact_status': 'MODEL_CLASSIFICATION_COMPLETE_UNIQUE_SELECTION_BLOCKED',
 'technical_best_model': 'SCALAR_GRADIENT',
 'technical_ranking_is_physical_selection': False,
 'selected_by_current_GVH_postulates': None,
 'new_postulate_required': True,
 'candidate_postulates': ['P-U1 scalar-clock gradient',
  'P-U2 independent unit vector',
  'P-U3 matter congruence'],
 'acceptance_requirements': ['Explicit physical principle',
  'Unique action or coefficient relations',
  'Stable linearized dynamics',
  'Recoverable GR limit',
  'At least one new falsifiable prediction',
  'No parameter values imported from observational fits'],
 'source_notebooks': ['0.2.21',
  '0.2.22',
  '0.2.23',
  '0.2.23.1',
  '0.2.23.2',
  '0.2.23.3.1']}

# 16. Exports

In [18]:
PREFIX = "GVH_Diagonal_Cubic_0.2.23.4.1"

exports = {
    "Source_Notebooks": source_notebooks_df,
    "Dependency_0.2.23.3.1": dependency_02331_df,
    "Models": models_df,
    "Criteria": criteria_df,
    "Evaluation": evaluation_df,
    "Score_Summary": score_summary_df,
    "Hard_Gate_Detail": hard_gate_detail_df,
    "Hard_Gate_Summary": hard_gate_summary_df,
    "GVH_Selection": gvh_selection_df,
    "Falsifiability": falsifiability_df,
    "Parameter_Burden": parameter_burden_df,
    "GR_Limit": gr_limit_df,
    "Candidate_Postulates": candidate_postulates_df,
    "Acceptance_Criteria": acceptance_criteria_df,
    "Decision": decision_df,
}

for suffix, table in exports.items():
    table.to_csv(
        EXPORT_DIR / f"{PREFIX}_{suffix}.csv",
        index=False,
    )

DECISION_FILE = (
    PROCESSED_DIR
    / "gvh_timelike_field_model_selection.json"
)

DECISION_FILE.write_text(
    json.dumps(
        decision_artifact,
        indent=2,
        ensure_ascii=False,
    ),
    encoding="utf-8",
)

metadata = {
    "notebook": (
        "GVH_Diagonal_Cubic_0.2.23.4.1_"
        "Timelike_Field_Model_Selection_and_Falsifiability"
    ),
    "execution_time_utc": datetime.now(
        timezone.utc
    ).isoformat(),
    "final_status": FINAL_STATUS,
    "all_sources_found": all_sources_found,
    "technical_best_model": technical_best_model,
    "unique_selection_pass": unique_selection_pass,
    "new_postulate_required": NEW_POSTULATE_REQUIRED,
    "decision_file": str(DECISION_FILE),
}

with (
    EXPORT_DIR / f"{PREFIX}_Metadata.json"
).open("w", encoding="utf-8") as file:
    json.dump(
        metadata,
        file,
        indent=2,
        ensure_ascii=False,
    )

print("Decision artifact :", DECISION_FILE)
print("Exports :", EXPORT_DIR)

Decision artifact : /content/Univers/gvh_diagonal_cubic/data/processed/timelike_field/gvh_timelike_field_model_selection.json
Exports : /content/Univers/gvh_diagonal_cubic/exports

# Conclusion

Le notebook classe techniquement les trois modèles de \(u^\mu\), mais ne transforme pas ce classement en choix physique.

Le résultat attendu est :

```text
PASS-MODEL-CLASSIFICATION-NO-UNIQUE-SELECTION
BLOCKED-NO-UNIQUE-MODEL-FROM-CURRENT-POSTULATES
NEW-FALSIFIABLE-POSTULATE-REQUIRED
```

Avant de dériver :

\[
\alpha_t,\qquad
\alpha_s,
\]

il faudra donc adopter ou dériver un principe physique explicite définissant \(u^\mu\).

Ce principe devra produire au moins une différence calculable avec la Relativité Générale sans utiliser les observations pour fixer rétroactivement ses paramètres.