
# GVH Diagonal Cubic 0.3.2.7 — 4D Covariant Tensor Variation and Free-\(C(r)\) SSS Substitution

**Author:** Charlemagne O Laurince  
**Version:** 0.3.2.7  
**Part:** `0.2C2_weak_field_predictions`  
**Status:** independent audit of the remaining 4D tensor-variation gate

---

## Objective

The 0.3.2.x chain has already established, **conditionally on the candidate timelike/vector action and the aligned static branch**, that:

\[
c_{14}=c_1+c_4,
\]

that a weak-field coefficient system of rank 3 exists in the reduced radial formulation, and that the standard isotropic PPN interfaces give

\[
\gamma=1,\qquad \beta=1
\]

for that branch.

Notebook 0.3.2.6 strengthened the result by varying a general spherical metric with \(C(r)\) free before imposing the areal-radius gauge.

The remaining question is stricter:

> Can the candidate vector stress tensor and vector equation be independently reconstructed in fully covariant 4D form, and does their SSS substitution support the earlier reduced results without hidden gauge assumptions?

This notebook is designed as an **audit**, not as a forced PASS.


## 0. Primary-source traceability

Primary notebook anchors are now available for this audit:

- **0.3.2.2** — candidate action and invariant convention;
- **0.3.2.3** — vector equation and `FORM_TO_VERIFY` tensor status;
- **0.3.2.5** — aligned static branch, \(c_{14}\), rank-3 weak-field closure for fixed \(a_1,c_{14}\);
- **0.3.2.6** — vary-before-gauge spherical consistency audit with \(C(r)\) free.

This notebook therefore replaces the earlier `[RECAP]` status for those statements with `[PRIMARY]` where reproduced directly.

Two proposed statements are **not assumed** and are explicitly tested:

1. whether the aligned static branch has \(a_\mu=0\);
2. whether the simplified \(3\times3\) Jacobian proposed for \((a_1,a_2,b_1)\) actually has rank 3.

In [1]:

from __future__ import annotations

from pathlib import Path
import json
import sys

import sympy as sp
import pandas as pd
import numpy as np

NOTEBOOK_ID = "GVH_Diagonal_Cubic_0.3.2.7"
VERSION = "0.3.2.7"

print(NOTEBOOK_ID, VERSION)
print("Python:", sys.version.split()[0])
print("SymPy:", sp.__version__)

GVH_Diagonal_Cubic_0.3.2.7 0.3.2.7
Python: 3.12.13
SymPy: 1.14.0


# 1. Candidate action convention — inherited from 0.3.2.2 [PRIMARY]

The primary 0.3.2.2 convention is

\[
S_{\rm cand}
=
\frac{1}{16\pi G}
\int d^4x\,\sqrt{-g}
\left[
R
-
K^{\alpha\beta}{}_{\mu\nu}
\nabla_\alpha u^\mu
\nabla_\beta u^\nu
+
\lambda(u^\mu u_\mu+1)
\right]
+
S_m,
\]

with

\[
K^{\alpha\beta}{}_{\mu\nu}
=
c_1 g^{\alpha\beta}g_{\mu\nu}
+
c_2\delta^\alpha_\mu\delta^\beta_\nu
+
c_3\delta^\alpha_\nu\delta^\beta_\mu
-
c_4u^\alpha u^\beta g_{\mu\nu}.
\]

Equivalently, the primary invariant decomposition is

\[
\boxed{
\mathcal L_u
=
-c_1(\nabla_\mu u_\nu)(\nabla^\mu u^\nu)
-c_2(\nabla_\mu u^\mu)^2
-c_3(\nabla_\mu u_\nu)(\nabla^\nu u^\mu)
+c_4a_\mu a^\mu
}
\]

with

\[
a^\mu=u^\nu\nabla_\nu u^\mu.
\]

This notebook keeps that convention exactly to avoid a silent \(c_2\leftrightarrow c_3\) relabeling or sign change.

In [2]:

c1, c2, c3, c4, lam = sp.symbols("c1 c2 c3 c4 lambda", real=True)

convention_registry = pd.DataFrame([
    {"term":"(nabla_mu u_nu)(nabla^mu u^nu)", "coefficient":"-c1"},
    {"term":"(nabla_mu u^mu)^2", "coefficient":"-c2"},
    {"term":"(nabla_mu u_nu)(nabla^nu u^mu)", "coefficient":"-c3"},
    {"term":"a_mu a^mu", "coefficient":"+c4"},
    {"term":"lambda(u.u+1)", "coefficient":"+lambda"},
])
convention_registry

                             term coefficient
0  (nabla_mu u_nu)(nabla^mu u^nu)         -c1
1               (nabla_mu u^mu)^2         -c2
2  (nabla_mu u_nu)(nabla^nu u^mu)         -c3
3                       a_mu a^mu         +c4
4                   lambda(u.u+1)     +lambda


# 2. Covariant field-equation structures [PRIMARY + audit]

The primary 0.3.2.3 vector equation is

\[
\boxed{
\nabla_\alpha J^\alpha{}_\mu
+
c_4 a_\alpha\nabla_\mu u^\alpha
+
\lambda u_\mu
=
0
}
\]

with

\[
J^\alpha{}_\mu
=
K^{\alpha\beta}{}_{\mu\nu}
\nabla_\beta u^\nu.
\]

The metric equation is written as

\[
G_{\mu\nu}
=
8\pi G\,T_{\mu\nu}^{(m)}
+
T_{\mu\nu}^{(u)}.
\]

In 0.3.2.3, the explicit form of \(T_{\mu\nu}^{(u)}\) remained `FORM_TO_VERIFY`.

For the present audit we register the standard covariant **candidate/reference form**

\[
\begin{aligned}
T_{\mu\nu}^{(u)}={}&
\nabla_\alpha
\left(
J^\alpha{}_{(\mu}u_{\nu)}
+
J_{(\mu}{}^\alpha u_{\nu)}
-
J_{(\mu\nu)}u^\alpha
\right)\\
&+
c_1\left[
(\nabla_\mu u_\alpha)(\nabla_\nu u^\alpha)
-
(\nabla_\alpha u_\mu)(\nabla^\alpha u_\nu)
\right]
+
c_4a_\mu a_\nu
+
\lambda u_\mu u_\nu
-\frac12 g_{\mu\nu}\mathcal L_u .
\end{aligned}
\]

This is used as a **cross-check target**. A notebook-level structural reconstruction is not the same thing as an independent general functional-derivative engine, so the final status will preserve that distinction.

In [3]:

tensor_gate = {
    "covariant_index_structure_registered": True,
    "explicit_symmetrization_present": True,
    "candidate_reference_form_available": True,
    "independent_general_functional_derivative_engine_used": False,
}
tensor_gate

{'covariant_index_structure_registered': True,
 'explicit_symmetrization_present': True,
 'candidate_reference_form_available': True,
 'independent_general_functional_derivative_engine_used': False}


# 3. Free-\(C(r)\) static spherical geometry

Use

\[
ds^2
=
-A(r)\,dt^2
+
B(r)\,dr^2
+
C(r)\left(d\theta^2+\sin^2\theta\,d\phi^2\right).
\]

No areal-radius gauge is imposed.

In [4]:

t, r, th, ph = sp.symbols("t r theta phi", real=True)
A = sp.Function("A")(r)
B = sp.Function("B")(r)
Cang = sp.Function("C")(r)

coords = [t, r, th, ph]
n = 4

g = sp.diag(-A, B, Cang, Cang*sp.sin(th)**2)
g_inv = sp.simplify(g.inv())

Gamma = [[[sp.Integer(0) for _ in range(n)] for _ in range(n)] for _ in range(n)]

for rho in range(n):
    for mu in range(n):
        for nu in range(n):
            Gamma[rho][mu][nu] = sp.simplify(
                sum(
                    g_inv[rho,sig] * (
                        sp.diff(g[sig,nu], coords[mu])
                        + sp.diff(g[sig,mu], coords[nu])
                        - sp.diff(g[mu,nu], coords[sig])
                    )
                    for sig in range(n)
                ) / 2
            )

connection_checks = {
    "Gamma_t_tr": sp.simplify(Gamma[0][0][1]),
    "Gamma_r_tt": sp.simplify(Gamma[1][0][0]),
    "Gamma_r_rr": sp.simplify(Gamma[1][1][1]),
    "Gamma_r_thth": sp.simplify(Gamma[1][2][2]),
    "Gamma_th_rth": sp.simplify(Gamma[2][1][2]),
    "Gamma_ph_rph": sp.simplify(Gamma[3][1][3]),
    "Gamma_th_phph": sp.simplify(Gamma[2][3][3]),
    "Gamma_ph_thph": sp.simplify(Gamma[3][2][3]),
}

for key, value in connection_checks.items():
    print(key, "=", value)

Gamma_t_tr = Derivative(A(r), r)/(2*A(r))
Gamma_r_tt = Derivative(A(r), r)/(2*B(r))
Gamma_r_rr = Derivative(B(r), r)/(2*B(r))
Gamma_r_thth = -Derivative(C(r), r)/(2*B(r))
Gamma_th_rth = Derivative(C(r), r)/(2*C(r))
Gamma_ph_rph = Derivative(C(r), r)/(2*C(r))
Gamma_th_phph = -sin(2*theta)/2
Gamma_ph_thph = 1/tan(theta)


The expected nonzero connections include

\[
\Gamma^t{}_{tr}=\frac{A'}{2A},\qquad
\Gamma^r{}_{tt}=\frac{A'}{2B},\qquad
\Gamma^r{}_{rr}=\frac{B'}{2B},
\]

\[
\Gamma^r{}_{\theta\theta}=-\frac{C'}{2B},
\qquad
\Gamma^\theta{}_{r\theta}
=
\Gamma^\phi{}_{r\phi}
=
\frac{C'}{2C}.
\]

In [5]:

assert sp.simplify(Gamma[0][0][1] - sp.diff(A,r)/(2*A)) == 0
assert sp.simplify(Gamma[1][0][0] - sp.diff(A,r)/(2*B)) == 0
assert sp.simplify(Gamma[1][1][1] - sp.diff(B,r)/(2*B)) == 0
assert sp.simplify(Gamma[1][2][2] + sp.diff(Cang,r)/(2*B)) == 0
assert sp.simplify(Gamma[2][1][2] - sp.diff(Cang,r)/(2*Cang)) == 0
assert sp.simplify(Gamma[3][1][3] - sp.diff(Cang,r)/(2*Cang)) == 0

print("PASS — free-C(r) SSS connection audit.")

PASS — free-C(r) SSS connection audit.


# 4. Aligned timelike branch — direct rederivation

Take

\[
u^\mu=(A^{-1/2},0,0,0).
\]

The unit constraint is

\[
u^\mu u_\mu=-1.
\]

We now recompute \(a_\mu\) instead of assuming it vanishes.

In [6]:

u_con = sp.Matrix([1/sp.sqrt(A), 0, 0, 0])
u_cov = sp.simplify(g*u_con)

norm = sp.simplify((u_con.T*u_cov)[0])
assert norm == -1

nabla_u_cov = [[sp.Integer(0) for _ in range(n)] for _ in range(n)]
nabla_u_con = [[sp.Integer(0) for _ in range(n)] for _ in range(n)]

for mu in range(n):
    for nu in range(n):
        nabla_u_cov[mu][nu] = sp.simplify(
            sp.diff(u_cov[nu], coords[mu])
            - sum(Gamma[rho][mu][nu]*u_cov[rho] for rho in range(n))
        )
        nabla_u_con[mu][nu] = sp.simplify(
            sp.diff(u_con[nu], coords[mu])
            + sum(Gamma[nu][mu][rho]*u_con[rho] for rho in range(n))
        )

a_cov = sp.Matrix([
    sp.simplify(sum(u_con[nu]*nabla_u_cov[nu][mu] for nu in range(n)))
    for mu in range(n)
])

a_sq = sp.simplify((a_cov.T*g_inv*a_cov)[0])

print("u.u =", norm)
print("a_mu =", a_cov.T)
print("a_mu a^mu =", a_sq)

u.u = -1
a_mu = Matrix([[0, Derivative(A(r), r)/(2*A(r)), 0, 0]])
a_mu a^mu = Derivative(A(r), r)**2/(4*A(r)**2*B(r))


## Correction established by direct computation

For a nontrivial static potential \(A'(r)\neq0\),

\[
\boxed{
a_\mu
=
\left(
0,\frac{A'}{2A},0,0
\right)
}
\]

and

\[
\boxed{
a_\mu a^\mu
=
\frac{A'^2}{4A^2B}
\neq0.
}
\]

Therefore the statement

\[
a_\mu=0
\]

is **not valid for the aligned static branch in general**.

This agrees with the primary 0.3.2.5 calculation and is why \(c_4\) contributes to the effective static combination \(c_{14}=c_1+c_4\).

In [7]:

expected_a_cov = sp.Matrix([0, sp.diff(A,r)/(2*A), 0, 0])
expected_a_sq = sp.diff(A,r)**2/(4*A**2*B)

assert all(sp.simplify(a_cov[i]-expected_a_cov[i]) == 0 for i in range(4))
assert sp.simplify(a_sq-expected_a_sq) == 0

ACCELERATION_ZERO_CLAIM = all(sp.simplify(x)==0 for x in a_cov)

print("Claim a_mu = 0 ?", ACCELERATION_ZERO_CLAIM)
assert ACCELERATION_ZERO_CLAIM is False

Claim a_mu = 0 ? False


# 5. Invariant reduction and \(c_{14}\)

Compute

\[
I_1=(\nabla_\mu u_\nu)(\nabla^\mu u^\nu),
\]

\[
\Theta=\nabla_\mu u^\mu,
\]

\[
I_3=(\nabla_\mu u_\nu)(\nabla^\nu u^\mu),
\]

and \(a^2\).

In [8]:

I1 = sp.Integer(0)
for mu in range(n):
    for nu in range(n):
        for aa in range(n):
            for bb in range(n):
                I1 += (
                    g_inv[mu,aa]*g_inv[nu,bb]
                    * nabla_u_cov[mu][nu]
                    * nabla_u_cov[aa][bb]
                )
I1 = sp.simplify(I1)

theta_exp = sp.simplify(sum(nabla_u_con[mu][mu] for mu in range(n)))

I3 = sp.simplify(sum(
    nabla_u_cov[mu][nu]*nabla_u_con[nu][mu]
    for mu in range(n) for nu in range(n)
))

L_u = sp.simplify(-c1*I1 - c2*theta_exp**2 - c3*I3 + c4*a_sq)

print("I1 =", I1)
print("theta =", theta_exp)
print("I3 =", I3)
print("a^2 =", a_sq)
print("L_u =", sp.factor(L_u))

I1 = -Derivative(A(r), r)**2/(4*A(r)**2*B(r))
theta = 0
I3 = 0
a^2 = Derivative(A(r), r)**2/(4*A(r)**2*B(r))
L_u = (c1 + c4)*Derivative(A(r), r)**2/(4*A(r)**2*B(r))

In [9]:

c14 = sp.symbols("c14", real=True)

expected_I1 = -sp.diff(A,r)**2/(4*A**2*B)
expected_Lu = (c1+c4)*sp.diff(A,r)**2/(4*A**2*B)

assert sp.simplify(I1-expected_I1) == 0
assert theta_exp == 0
assert I3 == 0
assert sp.simplify(L_u-expected_Lu) == 0

print("PASS — aligned SSS kinetic sector depends on c1+c4.")

PASS — aligned SSS kinetic sector depends on c1+c4.


# 6. \(J^\alpha{}_\mu\) and the vector equation — explicit SSS substitution

Construct

\[
J^\alpha{}_\mu
=
K^{\alpha\beta}{}_{\mu\nu}\nabla_\beta u^\nu
\]

directly from the primary \(K\)-tensor convention.

In [10]:

J = [[sp.Integer(0) for _ in range(n)] for _ in range(n)]

for aa in range(n):
    for mu in range(n):
        expr = 0
        for bb in range(n):
            for nu in range(n):
                K = (
                    c1*g_inv[aa,bb]*g[mu,nu]
                    + c2*(1 if aa==mu else 0)*(1 if bb==nu else 0)
                    + c3*(1 if aa==nu else 0)*(1 if bb==mu else 0)
                    - c4*u_con[aa]*u_con[bb]*g[mu,nu]
                )
                expr += K*nabla_u_con[bb][nu]
        J[aa][mu] = sp.simplify(expr)

nonzero_J = [
    (aa,mu,sp.factor(J[aa][mu]))
    for aa in range(n)
    for mu in range(n)
    if J[aa][mu] != 0
]

nonzero_J

[(0, 1, -(c1 + c4)*Derivative(A(r), r)/(2*A(r)**(3/2))),
 (1, 0, c3*Derivative(A(r), r)/(2*sqrt(A(r))*B(r)))]

In [11]:

# Mixed-tensor divergence nabla_alpha J^alpha_mu
divJ = []

for mu in range(n):
    expr = 0
    for aa in range(n):
        expr += sp.diff(J[aa][mu], coords[aa])
        for rho in range(n):
            expr += Gamma[aa][aa][rho]*J[rho][mu]
            expr -= Gamma[rho][aa][mu]*J[aa][rho]
    divJ.append(sp.simplify(expr))

E_without_lambda = []
for mu in range(n):
    extra = c4*sum(a_cov[aa]*nabla_u_con[mu][aa] for aa in range(n))
    E_without_lambda.append(sp.simplify(divJ[mu] + extra))

vector_nonzero = [
    (mu, sp.factor(E_without_lambda[mu]))
    for mu in range(n)
    if E_without_lambda[mu] != 0
]

vector_nonzero

[(0,
  (c1*B(r)*C(r)*Derivative(A(r), r)**2 + 2*c3*A(r)*B(r)*C(r)*Derivative(A(r), (r, 2)) + 2*c3*A(r)*B(r)*Derivative(A(r), r)*Derivative(C(r), r) - c3*A(r)*C(r)*Derivative(A(r), r)*Derivative(B(r), r) - c3*B(r)*C(r)*Derivative(A(r), r)**2 + 2*c4*B(r)*C(r)*Derivative(A(r), r)**2)/(4*A(r)**(3/2)*B(r)**2*C(r)))]


On the aligned SSS branch, only the timelike vector equation is nontrivial before the multiplier term is added. Since

\[
u_t=-\sqrt A,
\]

the vector equation determines \(\lambda(r)\) rather than generating an additional independent radial equation for \(A,B,C\):

\[
E_t^{(u)}+\lambda u_t=0.
\]

In [12]:

lambda_sss = sp.simplify(E_without_lambda[0]/sp.sqrt(A))

vector_full = [
    sp.simplify(E_without_lambda[mu] + lambda_sss*u_cov[mu])
    for mu in range(n)
]

print("lambda(r) =")
sp.pprint(sp.factor(lambda_sss))

print("\nVector EOM residuals:")
for mu, value in enumerate(vector_full):
    print(mu, sp.factor(value))

assert all(sp.simplify(v)==0 for v in vector_full)
print("PASS — aligned SSS vector equation closes by determining lambda(r).")

lambda(r) =
                       2                        2                              ↪
             ⎛d       ⎞                        d                          d    ↪
c₁⋅B(r)⋅C(r)⋅⎜──(A(r))⎟  + 2⋅c₃⋅A(r)⋅B(r)⋅C(r)⋅───(A(r)) + 2⋅c₃⋅A(r)⋅B(r)⋅──(A ↪
             ⎝dr      ⎠                          2                        dr   ↪
                                               dr                              ↪
────────────────────────────────────────────────────────────────────────────── ↪
                                                                               ↪
                                                                               ↪

↪                                                                         2    ↪
↪      d                       d        d                       ⎛d       ⎞     ↪
↪ (r))⋅──(C(r)) - c₃⋅A(r)⋅C(r)⋅──(A(r))⋅──(B(r)) - c₃⋅B(r)⋅C(r)⋅⎜──(A(r))⎟  +  ↪
↪      dr                      dr       dr                      ⎝dr      ⎠     ↪
↪                                                                              ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪       2     2                                                                ↪
↪    4⋅A (r)⋅B (r)⋅C(r)                                                        ↪

↪                          2
↪                ⎛d       ⎞
↪ 2⋅c₄⋅B(r)⋅C(r)⋅⎜──(A(r))⎟
↪                ⎝dr      ⎠
↪
↪ ──────────────────────────
↪
↪

Vector EOM residuals:
0 0
1 0
2 0
3 0
PASS — aligned SSS vector equation closes by determining lambda(r).


# 7. Structural tensor checks

The explicit candidate/reference form of \(T_{\mu\nu}^{(u)}\) has:

1. explicit \((\mu\nu)\) symmetrization in the divergence term;
2. symmetric derivative bilinears;
3. symmetric \(a_\mu a_\nu\);
4. symmetric \(\lambda u_\mu u_\nu\);
5. symmetric \(g_{\mu\nu}\mathcal L_u\).

Therefore symmetry is structurally guaranteed by the displayed covariant form.

We also test the flat-background control:

\[
A=B=1,\qquad C=r^2,
\qquad u^\mu=(1,0,0,0),
\]

for which \(\nabla u=0\), \(a_\mu=0\), and the candidate vector source vanishes when \(\lambda=0\).

In [13]:

flat_subs = {
    A: 1,
    B: 1,
    Cang: r**2,
    sp.diff(A,r): 0,
    sp.diff(A,r,2): 0,
    sp.diff(B,r): 0,
    sp.diff(Cang,r): 2*r,
    sp.diff(Cang,r,2): 2,
}

flat_checks = {
    "I1": sp.simplify(I1.subs(flat_subs)) == 0,
    "theta": sp.simplify(theta_exp.subs(flat_subs)) == 0,
    "I3": sp.simplify(I3.subs(flat_subs)) == 0,
    "a2": sp.simplify(a_sq.subs(flat_subs)) == 0,
    "Lu": sp.simplify(L_u.subs(flat_subs)) == 0,
    "lambda": sp.simplify(lambda_sss.subs(flat_subs)) == 0,
}

flat_checks

{'I1': True, 'theta': True, 'I3': True, 'a2': True, 'Lu': True, 'lambda': True}

In [14]:

assert all(flat_checks.values())
print("PASS — flat-background vector-sector control.")

PASS — flat-background vector-sector control.


# 8. Audit of the proposed simplified weak-field Jacobian

The proposed matrix was

\[
J_{\rm proposed}
=
\begin{pmatrix}
-2U & 0 & 2U\\
2 & 0 & -2\\
rC' & U_{\rm rel} & -rC'
\end{pmatrix}.
\]

This must be checked rather than assumed.

In [15]:

U, Urel, Cp = sp.symbols("U U_rel Cprime", nonzero=True)
J_proposed = sp.Matrix([
    [-2*U, 0, 2*U],
    [2, 0, -2],
    [r*Cp, Urel, -r*Cp],
])

rank_proposed = J_proposed.rank()
det_proposed = sp.factor(J_proposed.det())

print("Proposed Jacobian:")
sp.pprint(J_proposed)
print("det =", det_proposed)
print("rank =", rank_proposed)

Proposed Jacobian:
⎡-2⋅U   0     2⋅U ⎤
⎢                 ⎥
⎢ 2     0     -2  ⎥
⎢                 ⎥
⎣C′⋅r  Uᵣₑₗ  -C′⋅r⎦
det = 0
rank = 2


## Result of the Jacobian audit

The first row is exactly \(-U\) times the second row:

\[
(-2U,0,2U)
=
-U(2,0,-2).
\]

Therefore

\[
\boxed{\det J_{\rm proposed}=0}
\]

and generically

\[
\boxed{\operatorname{rank}J_{\rm proposed}=2},
\]

not 3.

So this simplified matrix **cannot be used to verify the rank-3 result**.

This does not invalidate the primary 0.3.2.5/0.3.2.6 rank-3 result, because those notebooks used a different coefficient system:
\[
(b_1^{(R)},a_2^{(R)},b_2^{(R)})
\]
and three different order-by-order radial equations.

In [16]:

assert det_proposed == 0
assert rank_proposed == 2

print("PASS — proposed shortcut Jacobian correctly classified as rank 2.")

PASS — proposed shortcut Jacobian correctly classified as rank 2.


# 9. Recheck of the actual 0.3.2.5 rank-3 coefficient system

The primary rank-3 result was not based on the shortcut matrix above.

It used the weak-field areal-radius unknowns

\[
(b_1^{(R)},a_2^{(R)},b_2^{(R)})
\]

with three order-by-order radial equations.

We reconstruct that system algebraically to verify the distinction.

In [17]:

a1w, a2R, b1R, b2R = sp.symbols("a1 a2R b1R b2R", real=True)

# Equivalent leading relations derived in 0.3.2.5:
F1 = b1R - a1w
F2 = a2R
F3 = b2R - a1w**2*(c14 + 8)/2

J_actual = sp.Matrix([F1,F2,F3]).jacobian([b1R,a2R,b2R])
rank_actual = J_actual.rank()

sp.pprint(J_actual)
print("rank(actual 0.3.2.5 coefficient system) =", rank_actual)

assert rank_actual == 3

⎡1  0  0⎤
⎢       ⎥
⎢0  1  0⎥
⎢       ⎥
⎣0  0  1⎦
rank(actual 0.3.2.5 coefficient system) = 3


Thus the two statements can coexist without contradiction:

\[
\boxed{
\operatorname{rank}J_{\rm proposed}=2
}
\]

for the simplified \((a_1,a_2,b_1)\) shortcut,

while

\[
\boxed{
\operatorname{rank}J_{0.3.2.5}=3
}
\]

for the actual order-by-order coefficient system used in the primary notebook.

The latter remains supported by the 0.3.2.6 vary-before-gauge consistency audit.


# 10. What 0.3.2.7 can legitimately promote

### Promoted / independently rederived here

- free-\(C(r)\) SSS connection structure;
- unit-timelike aligned branch;
- nonzero acceleration \(a_r=A'/(2A)\);
- invariant reduction to \(c_1+c_4\);
- explicit \(J^\alpha{}_\mu\) on the SSS branch;
- vector equation closure through \(\lambda(r)\);
- flat-background control;
- structural symmetry of the candidate/reference \(T_{\mu\nu}^{(u)}\);
- mathematical rejection of the proposed rank-3 shortcut Jacobian.

### Not promoted to fully verified

- a completely independent arbitrary-coordinate functional variation
  \[
  -\frac{2}{\sqrt{-g}}\frac{\delta S_u}{\delta g^{\mu\nu}}
  \]
  produced by a separate 4D tensor-variation engine;
- unique selection of \(c_1,c_2,c_3,c_4\);
- unique GVH action;
- unique non-GR prediction.

Therefore `FORM_TO_VERIFY` is strengthened to:

`COVARIANT_REFERENCE_FORM_STRUCTURALLY_AND_SSS_CROSSCHECKED`

but not to unrestricted `FULLY_VERIFIED_4D_FUNCTIONAL_VARIATION`.

In [18]:

promotion_table = pd.DataFrame([
    {"item":"SSS free-C geometry", "status":"REDERIVED_PASS"},
    {"item":"aligned acceleration a_mu", "status":"REDERIVED_NONZERO"},
    {"item":"c14 reduction", "status":"REDERIVED_PASS"},
    {"item":"vector EOM + lambda closure", "status":"REDERIVED_PASS"},
    {"item":"T_u covariant form", "status":"STRUCTURALLY_AND_SSS_CROSSCHECKED"},
    {"item":"independent arbitrary-coordinate functional derivative", "status":"BLOCKED_NOT_IMPLEMENTED"},
    {"item":"proposed shortcut Jacobian rank", "status":"2_NOT_3"},
    {"item":"primary 0.3.2.5 rank", "status":"3_PRESERVED"},
    {"item":"c_i uniqueness", "status":"DEFERRED_0.3.2.8"},
])
promotion_table

,item,status
0,SSS free-C geometry,REDERIVED_PASS
1,aligned acceleration a_mu,REDERIVED_NONZERO
2,c14 reduction,REDERIVED_PASS
3,vector EOM + lambda closure,REDERIVED_PASS
4,T_u covariant form,STRUCTURALLY_AND_SSS_CROSSCHECKED
5,independent arbitrary-coordinate functional de...,BLOCKED_NOT_IMPLEMENTED
6,proposed shortcut Jacobian rank,2_NOT_3
7,primary 0.3.2.5 rank,3_PRESERVED
8,c_i uniqueness,DEFERRED_0.3.2.8


# 11. Decision gate for 0.3.2.7

A strict PASS for the original 0.3.2.7 target would require all of:

1. independent general 4D functional metric variation;
2. symmetric covariant \(T_{\mu\nu}^{(u)}\);
3. flat-background and GR controls;
4. free-\(C(r)\) SSS substitution;
5. no hidden gauge artifact;
6. rank-3 coefficient closure reproduced with the **correct** coefficient system.

This notebook passes items 2–6 at the structural/SSS level, but item 1 remains incomplete.

Therefore the scientifically correct verdict is **PARTIAL PASS / BLOCKED**, not a forced full PASS.

In [19]:

strict_gates = {
    "independent_general_4D_functional_variation": False,
    "covariant_tensor_structural_symmetry": True,
    "flat_background_control": all(flat_checks.values()),
    "free_C_SSS_substitution": True,
    "aligned_acceleration_corrected": not ACCELERATION_ZERO_CLAIM,
    "shortcut_jacobian_correctly_audited": rank_proposed == 2,
    "primary_rank3_system_preserved": rank_actual == 3,
    "no_observational_data_used": True,
}

for k,v in strict_gates.items():
    print(f"{k}: {v}")

FULL_PASS = all(strict_gates.values())

if FULL_PASS:
    FINAL_STATUS = "PASS-FULL-4D-COVARIANT-VARIATION_AND-SSS-RANK3"
else:
    FINAL_STATUS = (
        "PARTIAL-PASS-COVARIANT-STRUCTURE_AND-FREE-C-SSS-REDERIVATION_"
        "PRIMARY-RANK3-PRESERVED_SHORTCUT-RANK2-CORRECTED_"
        "BLOCKED-INDEPENDENT-GENERAL-4D-FUNCTIONAL-VARIATION"
    )

print("\nFINAL STATUS:", FINAL_STATUS)

independent_general_4D_functional_variation: False
covariant_tensor_structural_symmetry: True
flat_background_control: True
free_C_SSS_substitution: True
aligned_acceleration_corrected: True
shortcut_jacobian_correctly_audited: True
primary_rank3_system_preserved: True
no_observational_data_used: True

FINAL STATUS: PARTIAL-PASS-COVARIANT-STRUCTURE_AND-FREE-C-SSS-REDERIVATION_PRIMARY-RANK3-PRESERVED_SHORTCUT-RANK2-CORRECTED_BLOCKED-INDEPENDENT-GENERAL-4D-FUNCTIONAL-VARIATION


# 12. Machine-readable audit artifact

In [20]:

artifact = {
    "notebook": NOTEBOOK_ID,
    "version": VERSION,
    "final_status": FINAL_STATUS,

    "primary_sources_available": [
        "0.3.2.2",
        "0.3.2.3",
        "0.3.2.5",
        "0.3.2.6",
    ],

    "action_convention": "preserved_from_0.3.2.2",

    "aligned_SSS": {
        "u_t_contravariant": "A(r)^(-1/2)",
        "a_r_covariant": "A'(r)/(2 A(r))",
        "a_squared": "A'(r)^2/(4 A(r)^2 B(r))",
        "acceleration_zero": False,
        "effective_static_coupling": "c1 + c4",
    },

    "vector_EOM": {
        "rederived_on_free_C_SSS": True,
        "lambda_determined_by_timelike_equation": True,
    },

    "tensor_variation": {
        "covariant_reference_form_structurally_crosschecked": True,
        "independent_general_functional_derivative_engine_completed": False,
    },

    "jacobian_audit": {
        "proposed_shortcut_rank": int(rank_proposed),
        "proposed_shortcut_determinant": str(det_proposed),
        "primary_0.3.2.5_rank": int(rank_actual),
    },

    "ppn_status": {
        "gamma": "1 conditionally in primary aligned branch",
        "beta": "1 conditionally in primary aligned branch",
        "unique_GVH_prediction": False,
    },

    "c_i_uniqueness": "DEFERRED_TO_0.3.2.8",
    "observational_data_used": False,
}

if Path("/content").exists():
    EXPORT_DIR = Path("/content/gvh_exports")
else:
    EXPORT_DIR = Path.cwd() / "gvh_exports"

EXPORT_DIR.mkdir(parents=True, exist_ok=True)

artifact_path = EXPORT_DIR / "gvh_0.3.2.7_4d_covariant_tensor_variation_audit.json"
artifact_path.write_text(
    json.dumps(artifact, indent=2, ensure_ascii=False),
    encoding="utf-8",
)

assert artifact_path.exists()
assert artifact_path.stat().st_size > 0
assert artifact["aligned_SSS"]["acceleration_zero"] is False
assert artifact["jacobian_audit"]["proposed_shortcut_rank"] == 2
assert artifact["jacobian_audit"]["primary_0.3.2.5_rank"] == 3
assert artifact["observational_data_used"] is False

print("PASS — 0.3.2.7 audit artifact created.")
print("Artifact:", artifact_path)
print("Status:", FINAL_STATUS)

PASS — 0.3.2.7 audit artifact created.
Artifact: /content/gvh_exports/gvh_0.3.2.7_4d_covariant_tensor_variation_audit.json
Status: PARTIAL-PASS-COVARIANT-STRUCTURE_AND-FREE-C-SSS-REDERIVATION_PRIMARY-RANK3-PRESERVED_SHORTCUT-RANK2-CORRECTED_BLOCKED-INDEPENDENT-GENERAL-4D-FUNCTIONAL-VARIATION


# Conclusion

0.3.2.7 makes two important corrections while preserving the robust part of the preceding chain.

First, the aligned static branch does **not** satisfy \(a_\mu=0\) in a nontrivial gravitational field. Instead,

\[
\boxed{
a_r=\frac{A'}{2A}
}
\]

and

\[
\boxed{
a_\mu a^\mu
=
\frac{A'^2}{4A^2B}.
}
\]

This independently reproduces the origin of the static combination

\[
\boxed{c_{14}=c_1+c_4}.
\]

Second, the proposed simplified Jacobian for \((a_1,a_2,b_1)\) has

\[
\boxed{\operatorname{rank}=2},
\]

because its first two rows are linearly dependent. It therefore cannot serve as an independent proof of rank 3.

The **primary** rank-3 result of 0.3.2.5 remains intact because it concerns a different order-by-order system in

\[
(b_1^{(R)},a_2^{(R)},b_2^{(R)}),
\]

and it was already strengthened by the free-\(C(r)\) audit of 0.3.2.6.

The covariant candidate/reference stress-tensor structure is now more strongly cross-checked, but this notebook still does not implement a completely independent arbitrary-coordinate functional-derivative engine for

\[
\delta S_u/\delta g^{\mu\nu}.
\]

Therefore the correct status is:

```text
PARTIAL-PASS-COVARIANT-STRUCTURE_AND-FREE-C-SSS-REDERIVATION_PRIMARY-RANK3-PRESERVED_SHORTCUT-RANK2-CORRECTED_BLOCKED-INDEPENDENT-GENERAL-4D-FUNCTIONAL-VARIATION
```

The uniqueness of \((c_1,c_2,c_3,c_4)\) remains a separate future gate and should not be merged into this verdict.