
# GVH Diagonal Cubic 0.2.2 — Christoffel Symbols
## Calcul automatique de \(\Gamma^\mu_{\alpha\beta}\)

**Auteur : Charlemagne O Laurince**

---

## Objectif

Ce notebook prolonge directement :

\[
\texttt{GVH\_Diagonal\_Cubic\_0.2.1\_Metric\_Foundations.ipynb}.
\]

Son objectif est de calculer automatiquement les symboles de Christoffel associés à une métrique diagonale cubique de la forme

\[
g_{\mu\nu}^{\mathrm{GVH}}
=
\operatorname{diag}
\left[
-A(r),\,B(r),\,B(r),\,B(r)
\right],
\]

dans les coordonnées cartésiennes isotropes

\[
X^\mu=(ct,x,y,z),
\qquad
r=\sqrt{x^2+y^2+z^2}.
\]

Les symboles de Christoffel sont définis par

\[
\Gamma^\mu_{\alpha\beta}
=
\frac{1}{2}g^{\mu\nu}
\left(
\partial_\alpha g_{\nu\beta}
+
\partial_\beta g_{\nu\alpha}
-
\partial_\nu g_{\alpha\beta}
\right).
\]

---

## Statut scientifique

Ce notebook ne propose pas encore une nouvelle loi physique GVH.

Il construit l'infrastructure mathématique nécessaire pour :

1. calculer les connexions géométriques ;
2. vérifier les limites connues ;
3. préparer l'intégration des géodésiques ;
4. tester ensuite une éventuelle métrique propre à GVH.

La métrique de Schwarzschild isotrope est utilisée ici comme **référence établie**, pas comme résultat nouveau de GVH.

In [1]:

import sympy as sp
import numpy as np
import pandas as pd

sp.init_printing()

print("SymPy version :", sp.__version__)

SymPy version : 1.14.0


# 1. Coordonnées et fonctions métriques

Nous utilisons :

\[
x^0=ct,\qquad x^1=x,\qquad x^2=y,\qquad x^3=z.
\]

La métrique est statique et isotrope spatialement :

\[
g_{00}=-A(r),
\qquad
g_{11}=g_{22}=g_{33}=B(r).
\]

Comme \(A\) et \(B\) dépendent uniquement de \(r\), les dérivées temporelles sont nulles.

In [2]:

# Coordonnées
ct, x, y, z = sp.symbols("ct x y z", real=True)
coords = (ct, x, y, z)

# Rayon isotrope
r = sp.sqrt(x**2 + y**2 + z**2)

# Fonctions métriques générales
A = sp.Function("A")(r)
B = sp.Function("B")(r)

# Métrique covariante
g_cov = sp.diag(-A, B, B, B)

# Métrique contravariante
g_contra = sp.simplify(g_cov.inv())

print("g_cov =")
display(g_cov)

print("g_contra =")
display(g_contra)

g_cov =

⎡  ⎛   ______________⎞                                                         ↪
⎢  ⎜  ╱  2    2    2 ⎟                                                         ↪
⎢-A⎝╲╱  x  + y  + z  ⎠           0                     0                     0 ↪
⎢                                                                              ↪
⎢                        ⎛   ______________⎞                                   ↪
⎢                        ⎜  ╱  2    2    2 ⎟                                   ↪
⎢          0            B⎝╲╱  x  + y  + z  ⎠           0                     0 ↪
⎢                                                                              ↪
⎢                                              ⎛   ______________⎞             ↪
⎢                                              ⎜  ╱  2    2    2 ⎟             ↪
⎢          0                     0            B⎝╲╱  x  + y  + z  ⎠           0 ↪
⎢                                                                              ↪
⎢                                                                    ⎛   _____ ↪
⎢                                                                    ⎜  ╱  2   ↪
⎣          0                     0                     0            B⎝╲╱  x  + ↪

↪           ⎤
↪           ⎥
↪           ⎥
↪           ⎥
↪           ⎥
↪           ⎥
↪           ⎥
↪           ⎥
↪           ⎥
↪           ⎥
↪           ⎥
↪           ⎥
↪ _________⎞⎥
↪   2    2 ⎟⎥
↪  y  + z  ⎠⎦

g_contra =

⎡        -1                                                                    ↪
⎢────────────────────           0                     0                     0  ↪
⎢ ⎛   ______________⎞                                                          ↪
⎢ ⎜  ╱  2    2    2 ⎟                                                          ↪
⎢A⎝╲╱  x  + y  + z  ⎠                                                          ↪
⎢                                                                              ↪
⎢                               1                                              ↪
⎢         0            ────────────────────           0                     0  ↪
⎢                       ⎛   ______________⎞                                    ↪
⎢                       ⎜  ╱  2    2    2 ⎟                                    ↪
⎢                      B⎝╲╱  x  + y  + z  ⎠                                    ↪
⎢                                                                              ↪
⎢                                                     1                        ↪
⎢         0                     0            ────────────────────           0  ↪
⎢                                             ⎛   ______________⎞              ↪
⎢                                             ⎜  ╱  2    2    2 ⎟              ↪
⎢                                            B⎝╲╱  x  + y  + z  ⎠              ↪
⎢                                                                              ↪
⎢                                                                           1  ↪
⎢         0                     0                     0            ─────────── ↪
⎢                                                                   ⎛   ______ ↪
⎢                                                                   ⎜  ╱  2    ↪
⎣                                                                  B⎝╲╱  x  +  ↪

↪          ⎤
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪          ⎥
↪ ─────────⎥
↪ ________⎞⎥
↪  2    2 ⎟⎥
↪ y  + z  ⎠⎦


# 2. Fonction générale de calcul des symboles de Christoffel

Le calcul est effectué directement à partir de la définition tensorielle.

La fonction suivante accepte :

- une matrice métrique covariante \(g_{\mu\nu}\) ;
- la liste des coordonnées ;
- une option de simplification.

Elle retourne un tableau tridimensionnel :

\[
\Gamma^\mu_{\alpha\beta}.
\]

In [3]:

def christoffel_symbols(metric_cov, coordinates, simplify_result=True):
    '''
    Calcule Gamma^mu_{alpha beta} à partir d'une métrique covariante.

    Parameters
    ----------
    metric_cov : sympy.Matrix
        Matrice g_{mu nu}.
    coordinates : tuple/list
        Coordonnées x^mu.
    simplify_result : bool
        Simplifier chaque composante.

    Returns
    -------
    Gamma : list
        Gamma[mu][alpha][beta].
    '''
    n = len(coordinates)

    if metric_cov.shape != (n, n):
        raise ValueError("La métrique doit être carrée et compatible avec les coordonnées.")

    metric_contra = sp.simplify(metric_cov.inv())

    Gamma = [[[sp.Integer(0) for beta in range(n)]
              for alpha in range(n)]
             for mu in range(n)]

    for mu in range(n):
        for alpha in range(n):
            for beta in range(n):
                expr = sp.Integer(0)

                for nu in range(n):
                    expr += metric_contra[mu, nu] * (
                        sp.diff(metric_cov[nu, beta], coordinates[alpha])
                        + sp.diff(metric_cov[nu, alpha], coordinates[beta])
                        - sp.diff(metric_cov[alpha, beta], coordinates[nu])
                    )

                expr = sp.Rational(1, 2) * expr
                Gamma[mu][alpha][beta] = (
                    sp.simplify(expr) if simplify_result else expr
                )

    return Gamma

Gamma_general = christoffel_symbols(g_cov, coords)
print("Calcul général terminé.")

Calcul général terminé.


# 3. Extraction des composantes non nulles

Pour une métrique diagonale, statique et isotrope, la majorité des composantes sont nulles.

Nous allons :

1. lister les composantes non nulles ;
2. vérifier la symétrie
   \[
   \Gamma^\mu_{\alpha\beta}
   =
   \Gamma^\mu_{\beta\alpha};
   \]
3. compter le nombre de composantes indépendantes non nulles.

In [4]:

def nonzero_christoffels(Gamma, simplify_test=True):
    rows = []
    n = len(Gamma)

    for mu in range(n):
        for alpha in range(n):
            for beta in range(n):
                expr = Gamma[mu][alpha][beta]
                test = sp.simplify(expr) if simplify_test else expr

                if test != 0:
                    rows.append({
                        "mu": mu,
                        "alpha": alpha,
                        "beta": beta,
                        "symbol": f"Gamma^{mu}_{{{alpha}{beta}}}",
                        "expression": test
                    })

    return rows

nonzero_general = nonzero_christoffels(Gamma_general)

print("Nombre total de composantes non nulles :", len(nonzero_general))
for row in nonzero_general:
    print(row["symbol"], "=", row["expression"])

Nombre total de composantes non nulles : 30
Gamma^0_{01} = x*Subs(Derivative(A(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*A(sqrt(x**2 + y**2 + z**2)))
Gamma^0_{02} = y*Subs(Derivative(A(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*A(sqrt(x**2 + y**2 + z**2)))
Gamma^0_{03} = z*Subs(Derivative(A(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*A(sqrt(x**2 + y**2 + z**2)))
Gamma^0_{10} = x*Subs(Derivative(A(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*A(sqrt(x**2 + y**2 + z**2)))
Gamma^0_{20} = y*Subs(Derivative(A(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*A(sqrt(x**2 + y**2 + z**2)))
Gamma^0_{30} = z*Subs(Derivative(A(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*A(sqrt(x**2 + y**2 + z**2)))
Gamma^1_{00} = x*Subs(Derivative(A(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^1_{11} = x*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^1_{12} = y*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^1_{13} = z*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^1_{21} = y*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^1_{22} = -x*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^1_{31} = z*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^1_{33} = -x*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^2_{00} = y*Subs(Derivative(A(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^2_{11} = -y*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^2_{12} = x*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^2_{21} = x*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^2_{22} = y*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^2_{23} = z*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^2_{32} = z*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^2_{33} = -y*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^3_{00} = z*Subs(Derivative(A(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^3_{11} = -z*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^3_{13} = x*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^3_{22} = -z*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^3_{23} = y*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^3_{31} = x*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^3_{32} = y*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))
Gamma^3_{33} = z*Subs(Derivative(B(_xi_1), _xi_1), _xi_1, sqrt(x**2 + y**2 + z**2))/(2*sqrt(x**2 + y**2 + z**2)*B(sqrt(x**2 + y**2 + z**2)))

In [5]:

def check_lower_index_symmetry(Gamma):
    n = len(Gamma)
    failures = []

    for mu in range(n):
        for alpha in range(n):
            for beta in range(n):
                delta = sp.simplify(
                    Gamma[mu][alpha][beta]
                    - Gamma[mu][beta][alpha]
                )
                if delta != 0:
                    failures.append((mu, alpha, beta, delta))

    return failures

symmetry_failures = check_lower_index_symmetry(Gamma_general)

if not symmetry_failures:
    print("Validation réussie : Gamma^mu_{alpha beta} = Gamma^mu_{beta alpha}.")
else:
    print("Échec de symétrie :", symmetry_failures)

Validation réussie : Gamma^mu_{alpha beta} = Gamma^mu_{beta alpha}.


# 4. Forme compacte avec dérivées radiales

Comme

\[
\partial_i r = \frac{x_i}{r},
\]

on a

\[
\partial_i A(r)
=
A'(r)\frac{x_i}{r},
\qquad
\partial_i B(r)
=
B'(r)\frac{x_i}{r}.
\]

Les principales composantes attendues sont :

\[
\Gamma^0_{0i}
=
\frac{A'(r)}{2A(r)}
\frac{x_i}{r},
\]

\[
\Gamma^i_{00}
=
\frac{A'(r)}{2B(r)}
\frac{x_i}{r},
\]

et les connexions spatiales dépendent de \(B'(r)/B(r)\).

In [6]:

# Quelques composantes représentatives
representative_components = {
    "Gamma^0_01": sp.simplify(Gamma_general[0][0][1]),
    "Gamma^0_02": sp.simplify(Gamma_general[0][0][2]),
    "Gamma^0_03": sp.simplify(Gamma_general[0][0][3]),
    "Gamma^1_00": sp.simplify(Gamma_general[1][0][0]),
    "Gamma^2_00": sp.simplify(Gamma_general[2][0][0]),
    "Gamma^3_00": sp.simplify(Gamma_general[3][0][0]),
    "Gamma^1_11": sp.simplify(Gamma_general[1][1][1]),
    "Gamma^1_22": sp.simplify(Gamma_general[1][2][2]),
    "Gamma^1_12": sp.simplify(Gamma_general[1][1][2]),
}

for name, expr in representative_components.items():
    print(name, "=")
    display(expr)

Gamma^0_01 =

    ⎛ d        ⎞│      ______________
  x⋅⎜───(A(ξ₁))⎟│     ╱  2    2    2
    ⎝dξ₁       ⎠│ξ₁=╲╱  x  + y  + z
────────────────────────────────────────
     ______________  ⎛   ______________⎞
    ╱  2    2    2   ⎜  ╱  2    2    2 ⎟
2⋅╲╱  x  + y  + z  ⋅A⎝╲╱  x  + y  + z  ⎠

Gamma^0_02 =

    ⎛ d        ⎞│      ______________
  y⋅⎜───(A(ξ₁))⎟│     ╱  2    2    2
    ⎝dξ₁       ⎠│ξ₁=╲╱  x  + y  + z
────────────────────────────────────────
     ______________  ⎛   ______________⎞
    ╱  2    2    2   ⎜  ╱  2    2    2 ⎟
2⋅╲╱  x  + y  + z  ⋅A⎝╲╱  x  + y  + z  ⎠

Gamma^0_03 =

    ⎛ d        ⎞│      ______________
  z⋅⎜───(A(ξ₁))⎟│     ╱  2    2    2
    ⎝dξ₁       ⎠│ξ₁=╲╱  x  + y  + z
────────────────────────────────────────
     ______________  ⎛   ______________⎞
    ╱  2    2    2   ⎜  ╱  2    2    2 ⎟
2⋅╲╱  x  + y  + z  ⋅A⎝╲╱  x  + y  + z  ⎠

Gamma^1_00 =

    ⎛ d        ⎞│      ______________
  x⋅⎜───(A(ξ₁))⎟│     ╱  2    2    2
    ⎝dξ₁       ⎠│ξ₁=╲╱  x  + y  + z
────────────────────────────────────────
     ______________  ⎛   ______________⎞
    ╱  2    2    2   ⎜  ╱  2    2    2 ⎟
2⋅╲╱  x  + y  + z  ⋅B⎝╲╱  x  + y  + z  ⎠

Gamma^2_00 =

    ⎛ d        ⎞│      ______________
  y⋅⎜───(A(ξ₁))⎟│     ╱  2    2    2
    ⎝dξ₁       ⎠│ξ₁=╲╱  x  + y  + z
────────────────────────────────────────
     ______________  ⎛   ______________⎞
    ╱  2    2    2   ⎜  ╱  2    2    2 ⎟
2⋅╲╱  x  + y  + z  ⋅B⎝╲╱  x  + y  + z  ⎠

Gamma^3_00 =

    ⎛ d        ⎞│      ______________
  z⋅⎜───(A(ξ₁))⎟│     ╱  2    2    2
    ⎝dξ₁       ⎠│ξ₁=╲╱  x  + y  + z
────────────────────────────────────────
     ______________  ⎛   ______________⎞
    ╱  2    2    2   ⎜  ╱  2    2    2 ⎟
2⋅╲╱  x  + y  + z  ⋅B⎝╲╱  x  + y  + z  ⎠

Gamma^1_11 =

    ⎛ d        ⎞│      ______________
  x⋅⎜───(B(ξ₁))⎟│     ╱  2    2    2
    ⎝dξ₁       ⎠│ξ₁=╲╱  x  + y  + z
────────────────────────────────────────
     ______________  ⎛   ______________⎞
    ╱  2    2    2   ⎜  ╱  2    2    2 ⎟
2⋅╲╱  x  + y  + z  ⋅B⎝╲╱  x  + y  + z  ⎠

Gamma^1_22 =

    ⎛ d        ⎞│      ______________
 -x⋅⎜───(B(ξ₁))⎟│     ╱  2    2    2
    ⎝dξ₁       ⎠│ξ₁=╲╱  x  + y  + z
────────────────────────────────────────
     ______________  ⎛   ______________⎞
    ╱  2    2    2   ⎜  ╱  2    2    2 ⎟
2⋅╲╱  x  + y  + z  ⋅B⎝╲╱  x  + y  + z  ⎠

Gamma^1_12 =

    ⎛ d        ⎞│      ______________
  y⋅⎜───(B(ξ₁))⎟│     ╱  2    2    2
    ⎝dξ₁       ⎠│ξ₁=╲╱  x  + y  + z
────────────────────────────────────────
     ______________  ⎛   ______________⎞
    ╱  2    2    2   ⎜  ╱  2    2    2 ⎟
2⋅╲╱  x  + y  + z  ⋅B⎝╲╱  x  + y  + z  ⎠


# 5. Test de référence 1 — Métrique de Minkowski

Dans l'espace-temps plat :

\[
A(r)=1,
\qquad
B(r)=1.
\]

Toutes les dérivées métriques sont nulles. On doit donc obtenir :

\[
\Gamma^\mu_{\alpha\beta}=0.
\]

Ce test vérifie que l'algorithme ne génère pas de fausse connexion géométrique.

In [7]:

g_minkowski = sp.diag(-1, 1, 1, 1)
Gamma_minkowski = christoffel_symbols(g_minkowski, coords)
nonzero_minkowski = nonzero_christoffels(Gamma_minkowski)

print("Nombre de Christoffel non nuls pour Minkowski :", len(nonzero_minkowski))
assert len(nonzero_minkowski) == 0

print("Test Minkowski réussi.")

Nombre de Christoffel non nuls pour Minkowski : 0
Test Minkowski réussi.


# 6. Test de référence 2 — Schwarzschild en coordonnées isotropes

Introduisons

\[
\chi(\rho)=\frac{GM}{c^2\rho},
\qquad
q=\frac{\chi}{2}.
\]

La métrique de Schwarzschild isotrope s'écrit :

\[
A_{\mathrm{Schw}}(\rho)
=
\left(
\frac{1-q}{1+q}
\right)^2,
\]

\[
B_{\mathrm{Schw}}(\rho)
=
(1+q)^4.
\]

Cette forme est diagonale dans les coordonnées cartésiennes isotropes.

In [8]:

G, M, c = sp.symbols("G M c", positive=True, finite=True)

chi = G*M/(c**2*r)
q = chi/2

A_schw = sp.simplify(((1-q)/(1+q))**2)
B_schw = sp.simplify((1+q)**4)

g_schw_iso = sp.diag(-A_schw, B_schw, B_schw, B_schw)

print("A_schw =")
display(A_schw)

print("B_schw =")
display(B_schw)

A_schw =

                              2
⎛              ______________⎞
⎜         2   ╱  2    2    2 ⎟
⎝G⋅M - 2⋅c ⋅╲╱  x  + y  + z  ⎠
───────────────────────────────
                              2
⎛              ______________⎞
⎜         2   ╱  2    2    2 ⎟
⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠

B_schw =

                              4
⎛              ______________⎞
⎜         2   ╱  2    2    2 ⎟
⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠
───────────────────────────────
                         2
         8 ⎛ 2    2    2⎞
     16⋅c ⋅⎝x  + y  + z ⎠

In [9]:

Gamma_schw = christoffel_symbols(g_schw_iso, coords)
nonzero_schw = nonzero_christoffels(Gamma_schw)

print("Nombre de composantes non nulles pour Schwarzschild isotrope :",
      len(nonzero_schw))

# Afficher seulement quelques composantes représentatives
for item in nonzero_schw[:12]:
    print(item["symbol"], "=")
    display(sp.factor(item["expression"]))

Nombre de composantes non nulles pour Schwarzschild isotrope : 30
Gamma^0_{01} =

              ⎛               ______________⎞ ⎛                    ___________ ↪
          2   ⎜          2   ╱  2    2    2 ⎟ ⎜ 2  2          2   ╱  2    2    ↪
   4⋅G⋅M⋅c ⋅x⋅⎝-G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝G ⋅M  + 4⋅G⋅M⋅c ⋅╲╱  x  + y  +  ↪
────────────────────────────────────────────────────────────────────────────── ↪
                              3                                                ↪
⎛              ______________⎞     ______________ ⎛                    _______ ↪
⎜         2   ╱  2    2    2 ⎟    ╱  2    2    2  ⎜ 2  2          2   ╱  2     ↪
⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠ ⋅╲╱  x  + y  + z  ⋅⎝G ⋅M  - 4⋅G⋅M⋅c ⋅╲╱  x  + y ↪

↪ ___                              ⎞
↪  2       4  2      4  2      4  2⎟
↪ z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠
↪ ──────────────────────────────────────
↪
↪ _______                              ⎞
↪ 2    2       4  2      4  2      4  2⎟
↪   + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠

Gamma^0_{02} =

              ⎛               ______________⎞ ⎛                    ___________ ↪
          2   ⎜          2   ╱  2    2    2 ⎟ ⎜ 2  2          2   ╱  2    2    ↪
   4⋅G⋅M⋅c ⋅y⋅⎝-G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝G ⋅M  + 4⋅G⋅M⋅c ⋅╲╱  x  + y  +  ↪
────────────────────────────────────────────────────────────────────────────── ↪
                              3                                                ↪
⎛              ______________⎞     ______________ ⎛                    _______ ↪
⎜         2   ╱  2    2    2 ⎟    ╱  2    2    2  ⎜ 2  2          2   ╱  2     ↪
⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠ ⋅╲╱  x  + y  + z  ⋅⎝G ⋅M  - 4⋅G⋅M⋅c ⋅╲╱  x  + y ↪

↪ ___                              ⎞
↪  2       4  2      4  2      4  2⎟
↪ z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠
↪ ──────────────────────────────────────
↪
↪ _______                              ⎞
↪ 2    2       4  2      4  2      4  2⎟
↪   + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠

Gamma^0_{03} =

              ⎛               ______________⎞ ⎛                    ___________ ↪
          2   ⎜          2   ╱  2    2    2 ⎟ ⎜ 2  2          2   ╱  2    2    ↪
   4⋅G⋅M⋅c ⋅z⋅⎝-G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝G ⋅M  + 4⋅G⋅M⋅c ⋅╲╱  x  + y  +  ↪
────────────────────────────────────────────────────────────────────────────── ↪
                              3                                                ↪
⎛              ______________⎞     ______________ ⎛                    _______ ↪
⎜         2   ╱  2    2    2 ⎟    ╱  2    2    2  ⎜ 2  2          2   ╱  2     ↪
⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠ ⋅╲╱  x  + y  + z  ⋅⎝G ⋅M  - 4⋅G⋅M⋅c ⋅╲╱  x  + y ↪

↪ ___                              ⎞
↪  2       4  2      4  2      4  2⎟
↪ z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠
↪ ──────────────────────────────────────
↪
↪ _______                              ⎞
↪ 2    2       4  2      4  2      4  2⎟
↪   + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠

Gamma^0_{10} =

              ⎛               ______________⎞ ⎛                    ___________ ↪
          2   ⎜          2   ╱  2    2    2 ⎟ ⎜ 2  2          2   ╱  2    2    ↪
   4⋅G⋅M⋅c ⋅x⋅⎝-G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝G ⋅M  + 4⋅G⋅M⋅c ⋅╲╱  x  + y  +  ↪
────────────────────────────────────────────────────────────────────────────── ↪
                              3                                                ↪
⎛              ______________⎞     ______________ ⎛                    _______ ↪
⎜         2   ╱  2    2    2 ⎟    ╱  2    2    2  ⎜ 2  2          2   ╱  2     ↪
⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠ ⋅╲╱  x  + y  + z  ⋅⎝G ⋅M  - 4⋅G⋅M⋅c ⋅╲╱  x  + y ↪

↪ ___                              ⎞
↪  2       4  2      4  2      4  2⎟
↪ z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠
↪ ──────────────────────────────────────
↪
↪ _______                              ⎞
↪ 2    2       4  2      4  2      4  2⎟
↪   + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠

Gamma^0_{20} =

              ⎛               ______________⎞ ⎛                    ___________ ↪
          2   ⎜          2   ╱  2    2    2 ⎟ ⎜ 2  2          2   ╱  2    2    ↪
   4⋅G⋅M⋅c ⋅y⋅⎝-G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝G ⋅M  + 4⋅G⋅M⋅c ⋅╲╱  x  + y  +  ↪
────────────────────────────────────────────────────────────────────────────── ↪
                              3                                                ↪
⎛              ______________⎞     ______________ ⎛                    _______ ↪
⎜         2   ╱  2    2    2 ⎟    ╱  2    2    2  ⎜ 2  2          2   ╱  2     ↪
⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠ ⋅╲╱  x  + y  + z  ⋅⎝G ⋅M  - 4⋅G⋅M⋅c ⋅╲╱  x  + y ↪

↪ ___                              ⎞
↪  2       4  2      4  2      4  2⎟
↪ z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠
↪ ──────────────────────────────────────
↪
↪ _______                              ⎞
↪ 2    2       4  2      4  2      4  2⎟
↪   + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠

Gamma^0_{30} =

              ⎛               ______________⎞ ⎛                    ___________ ↪
          2   ⎜          2   ╱  2    2    2 ⎟ ⎜ 2  2          2   ╱  2    2    ↪
   4⋅G⋅M⋅c ⋅z⋅⎝-G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝G ⋅M  + 4⋅G⋅M⋅c ⋅╲╱  x  + y  +  ↪
────────────────────────────────────────────────────────────────────────────── ↪
                              3                                                ↪
⎛              ______________⎞     ______________ ⎛                    _______ ↪
⎜         2   ╱  2    2    2 ⎟    ╱  2    2    2  ⎜ 2  2          2   ╱  2     ↪
⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠ ⋅╲╱  x  + y  + z  ⋅⎝G ⋅M  - 4⋅G⋅M⋅c ⋅╲╱  x  + y ↪

↪ ___                              ⎞
↪  2       4  2      4  2      4  2⎟
↪ z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠
↪ ──────────────────────────────────────
↪
↪ _______                              ⎞
↪ 2    2       4  2      4  2      4  2⎟
↪   + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠

Gamma^1_{00} =

                                                                               ↪
                                                                               ↪
                                                                               ↪
────────────────────────────────────────────────────────────────────────────── ↪
                              3                                                ↪
⎛              ______________⎞  ⎛                      ______________          ↪
⎜         2   ╱  2    2    2 ⎟  ⎜ 4  4      3  3  2   ╱  2    2    2        2  ↪
⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠ ⋅⎝G ⋅M  + 8⋅G ⋅M ⋅c ⋅╲╱  x  + y  + z   + 24⋅G ⋅ ↪

↪                                                    ⎛               _________ ↪
↪                                               10   ⎜          2   ╱  2    2  ↪
↪                                       64⋅G⋅M⋅c  ⋅x⋅⎝-G⋅M + 2⋅c ⋅╲╱  x  + y   ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                                                              ↪
↪                                                              ______________  ↪
↪  2  4  2       2  2  4  2       2  2  4  2           6  2   ╱  2    2    2   ↪
↪ M ⋅c ⋅x  + 24⋅G ⋅M ⋅c ⋅y  + 24⋅G ⋅M ⋅c ⋅z  + 32⋅G⋅M⋅c ⋅x ⋅╲╱  x  + y  + z    ↪

↪ _____⎞               3/2                                                     ↪
↪    2 ⎟ ⎛ 2    2    2⎞                                                        ↪
↪ + z  ⎠⋅⎝x  + y  + z ⎠                                                        ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                                                              ↪
↪                   ______________                   ______________            ↪
↪           6  2   ╱  2    2    2            6  2   ╱  2    2    2        8  4 ↪
↪ + 32⋅G⋅M⋅c ⋅y ⋅╲╱  x  + y  + z   + 32⋅G⋅M⋅c ⋅z ⋅╲╱  x  + y  + z   + 16⋅c ⋅x  ↪

↪
↪
↪
↪ ─────────────────────────────────────────────────────────────────
↪
↪                                                                 ⎞
↪        8  2  2       8  2  2       8  4       8  2  2       8  4⎟
↪  + 32⋅c ⋅x ⋅y  + 32⋅c ⋅x ⋅z  + 16⋅c ⋅y  + 32⋅c ⋅y ⋅z  + 16⋅c ⋅z ⎠

Gamma^1_{11} =

                                                                               ↪
                                                                               ↪
                                                                               ↪
                                                                               ↪
────────────────────────────────────────────────────────────────────────────── ↪
               ⎛                      ______________                           ↪
⎛ 2    2    2⎞ ⎜ 4  4      3  3  2   ╱  2    2    2        2  2  4  2       2  ↪
⎝x  + y  + z ⎠⋅⎝G ⋅M  + 8⋅G ⋅M ⋅c ⋅╲╱  x  + y  + z   + 24⋅G ⋅M ⋅c ⋅x  + 24⋅G ⋅ ↪

↪                                                                              ↪
↪                                                  ⎛              ____________ ↪
↪                                                  ⎜         2   ╱  2    2     ↪
↪                                         -2⋅G⋅M⋅x⋅⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                             ______________                   ↪
↪  2  4  2       2  2  4  2           6  2   ╱  2    2    2            6  2    ↪
↪ M ⋅c ⋅y  + 24⋅G ⋅M ⋅c ⋅z  + 32⋅G⋅M⋅c ⋅x ⋅╲╱  x  + y  + z   + 32⋅G⋅M⋅c ⋅y ⋅╲╱ ↪

↪    3                                                                         ↪
↪ __⎞                                                                          ↪
↪ 2 ⎟                                                                          ↪
↪   ⎠                                                                          ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪  ______________                   ______________                             ↪
↪ ╱  2    2    2            6  2   ╱  2    2    2        8  4       8  2  2    ↪
↪   x  + y  + z   + 32⋅G⋅M⋅c ⋅z ⋅╲╱  x  + y  + z   + 16⋅c ⋅x  + 32⋅c ⋅x ⋅y  +  ↪

↪
↪
↪
↪
↪ ────────────────────────────────────────────────
↪                                                ⎞
↪     8  2  2       8  4       8  2  2       8  4⎟
↪ 32⋅c ⋅x ⋅z  + 16⋅c ⋅y  + 32⋅c ⋅y ⋅z  + 16⋅c ⋅z ⎠

Gamma^1_{12} =

                                                                               ↪
                                                                               ↪
                                                                               ↪
                                                                               ↪
────────────────────────────────────────────────────────────────────────────── ↪
               ⎛                      ______________                           ↪
⎛ 2    2    2⎞ ⎜ 4  4      3  3  2   ╱  2    2    2        2  2  4  2       2  ↪
⎝x  + y  + z ⎠⋅⎝G ⋅M  + 8⋅G ⋅M ⋅c ⋅╲╱  x  + y  + z   + 24⋅G ⋅M ⋅c ⋅x  + 24⋅G ⋅ ↪

↪                                                                              ↪
↪                                                  ⎛              ____________ ↪
↪                                                  ⎜         2   ╱  2    2     ↪
↪                                         -2⋅G⋅M⋅y⋅⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                             ______________                   ↪
↪  2  4  2       2  2  4  2           6  2   ╱  2    2    2            6  2    ↪
↪ M ⋅c ⋅y  + 24⋅G ⋅M ⋅c ⋅z  + 32⋅G⋅M⋅c ⋅x ⋅╲╱  x  + y  + z   + 32⋅G⋅M⋅c ⋅y ⋅╲╱ ↪

↪    3                                                                         ↪
↪ __⎞                                                                          ↪
↪ 2 ⎟                                                                          ↪
↪   ⎠                                                                          ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪  ______________                   ______________                             ↪
↪ ╱  2    2    2            6  2   ╱  2    2    2        8  4       8  2  2    ↪
↪   x  + y  + z   + 32⋅G⋅M⋅c ⋅z ⋅╲╱  x  + y  + z   + 16⋅c ⋅x  + 32⋅c ⋅x ⋅y  +  ↪

↪
↪
↪
↪
↪ ────────────────────────────────────────────────
↪                                                ⎞
↪     8  2  2       8  4       8  2  2       8  4⎟
↪ 32⋅c ⋅x ⋅z  + 16⋅c ⋅y  + 32⋅c ⋅y ⋅z  + 16⋅c ⋅z ⎠

Gamma^1_{13} =

                                                                               ↪
                                                                               ↪
                                                                               ↪
                                                                               ↪
────────────────────────────────────────────────────────────────────────────── ↪
               ⎛                      ______________                           ↪
⎛ 2    2    2⎞ ⎜ 4  4      3  3  2   ╱  2    2    2        2  2  4  2       2  ↪
⎝x  + y  + z ⎠⋅⎝G ⋅M  + 8⋅G ⋅M ⋅c ⋅╲╱  x  + y  + z   + 24⋅G ⋅M ⋅c ⋅x  + 24⋅G ⋅ ↪

↪                                                                              ↪
↪                                                  ⎛              ____________ ↪
↪                                                  ⎜         2   ╱  2    2     ↪
↪                                         -2⋅G⋅M⋅z⋅⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                             ______________                   ↪
↪  2  4  2       2  2  4  2           6  2   ╱  2    2    2            6  2    ↪
↪ M ⋅c ⋅y  + 24⋅G ⋅M ⋅c ⋅z  + 32⋅G⋅M⋅c ⋅x ⋅╲╱  x  + y  + z   + 32⋅G⋅M⋅c ⋅y ⋅╲╱ ↪

↪    3                                                                         ↪
↪ __⎞                                                                          ↪
↪ 2 ⎟                                                                          ↪
↪   ⎠                                                                          ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪  ______________                   ______________                             ↪
↪ ╱  2    2    2            6  2   ╱  2    2    2        8  4       8  2  2    ↪
↪   x  + y  + z   + 32⋅G⋅M⋅c ⋅z ⋅╲╱  x  + y  + z   + 16⋅c ⋅x  + 32⋅c ⋅x ⋅y  +  ↪

↪
↪
↪
↪
↪ ────────────────────────────────────────────────
↪                                                ⎞
↪     8  2  2       8  4       8  2  2       8  4⎟
↪ 32⋅c ⋅x ⋅z  + 16⋅c ⋅y  + 32⋅c ⋅y ⋅z  + 16⋅c ⋅z ⎠

Gamma^1_{21} =

                                                                               ↪
                                                                               ↪
                                                                               ↪
                                                                               ↪
────────────────────────────────────────────────────────────────────────────── ↪
               ⎛                      ______________                           ↪
⎛ 2    2    2⎞ ⎜ 4  4      3  3  2   ╱  2    2    2        2  2  4  2       2  ↪
⎝x  + y  + z ⎠⋅⎝G ⋅M  + 8⋅G ⋅M ⋅c ⋅╲╱  x  + y  + z   + 24⋅G ⋅M ⋅c ⋅x  + 24⋅G ⋅ ↪

↪                                                                              ↪
↪                                                  ⎛              ____________ ↪
↪                                                  ⎜         2   ╱  2    2     ↪
↪                                         -2⋅G⋅M⋅y⋅⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                             ______________                   ↪
↪  2  4  2       2  2  4  2           6  2   ╱  2    2    2            6  2    ↪
↪ M ⋅c ⋅y  + 24⋅G ⋅M ⋅c ⋅z  + 32⋅G⋅M⋅c ⋅x ⋅╲╱  x  + y  + z   + 32⋅G⋅M⋅c ⋅y ⋅╲╱ ↪

↪    3                                                                         ↪
↪ __⎞                                                                          ↪
↪ 2 ⎟                                                                          ↪
↪   ⎠                                                                          ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪  ______________                   ______________                             ↪
↪ ╱  2    2    2            6  2   ╱  2    2    2        8  4       8  2  2    ↪
↪   x  + y  + z   + 32⋅G⋅M⋅c ⋅z ⋅╲╱  x  + y  + z   + 16⋅c ⋅x  + 32⋅c ⋅x ⋅y  +  ↪

↪
↪
↪
↪
↪ ────────────────────────────────────────────────
↪                                                ⎞
↪     8  2  2       8  4       8  2  2       8  4⎟
↪ 32⋅c ⋅x ⋅z  + 16⋅c ⋅y  + 32⋅c ⋅y ⋅z  + 16⋅c ⋅z ⎠

Gamma^1_{22} =

                                                                               ↪
                                                                               ↪
                                                                               ↪
                                                                               ↪
────────────────────────────────────────────────────────────────────────────── ↪
               ⎛                      ______________                           ↪
⎛ 2    2    2⎞ ⎜ 4  4      3  3  2   ╱  2    2    2        2  2  4  2       2  ↪
⎝x  + y  + z ⎠⋅⎝G ⋅M  + 8⋅G ⋅M ⋅c ⋅╲╱  x  + y  + z   + 24⋅G ⋅M ⋅c ⋅x  + 24⋅G ⋅ ↪

↪                                                                              ↪
↪                                                  ⎛              ____________ ↪
↪                                                  ⎜         2   ╱  2    2     ↪
↪                                          2⋅G⋅M⋅x⋅⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                             ______________                   ↪
↪  2  4  2       2  2  4  2           6  2   ╱  2    2    2            6  2    ↪
↪ M ⋅c ⋅y  + 24⋅G ⋅M ⋅c ⋅z  + 32⋅G⋅M⋅c ⋅x ⋅╲╱  x  + y  + z   + 32⋅G⋅M⋅c ⋅y ⋅╲╱ ↪

↪    3                                                                         ↪
↪ __⎞                                                                          ↪
↪ 2 ⎟                                                                          ↪
↪   ⎠                                                                          ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪  ______________                   ______________                             ↪
↪ ╱  2    2    2            6  2   ╱  2    2    2        8  4       8  2  2    ↪
↪   x  + y  + z   + 32⋅G⋅M⋅c ⋅z ⋅╲╱  x  + y  + z   + 16⋅c ⋅x  + 32⋅c ⋅x ⋅y  +  ↪

↪
↪
↪
↪
↪ ────────────────────────────────────────────────
↪                                                ⎞
↪     8  2  2       8  4       8  2  2       8  4⎟
↪ 32⋅c ⋅x ⋅z  + 16⋅c ⋅y  + 32⋅c ⋅y ⋅z  + 16⋅c ⋅z ⎠


# 7. Limite de champ faible

Lorsque

\[
\chi=\frac{GM}{c^2r}\ll1,
\]

on attend :

\[
A_{\mathrm{Schw}}
=
1-2\chi+2\chi^2+\mathcal O(\chi^3),
\]

\[
B_{\mathrm{Schw}}
=
1+2\chi+\frac{3}{2}\chi^2+\mathcal O(\chi^3).
\]

Nous vérifions les séries symboliquement.

In [10]:

eps = sp.symbols("eps", real=True)

A_eps = ((1-eps/2)/(1+eps/2))**2
B_eps = (1+eps/2)**4

A_series = sp.series(A_eps, eps, 0, 4)
B_series = sp.series(B_eps, eps, 0, 4)

print("Développement de A :")
display(A_series)

print("Développement de B :")
display(B_series)

Développement de A :

                          3
                 2   3⋅eps     ⎛   4⎞
1 - 2⋅eps + 2⋅eps  - ────── + O⎝eps ⎠
                       2

Développement de B :

                 2      3
            3⋅eps    eps     ⎛   4⎞
1 + 2⋅eps + ────── + ──── + O⎝eps ⎠
              2       2


# 8. Récupération de l'accélération newtonienne

Dans la limite faible et lente, l'équation géodésique spatiale est dominée par

\[
\frac{d^2x^i}{dt^2}
\approx
-c^2\Gamma^i_{00}.
\]

Avec

\[
g_{00}
\approx
-\left(1+\frac{2\Phi}{c^2}\right),
\]

on doit retrouver

\[
\frac{d^2x^i}{dt^2}
=
-\partial_i\Phi.
\]

Pour

\[
\Phi=-\frac{GM}{r},
\]

cela donne

\[
\mathbf a
=
-\frac{GM}{r^3}\mathbf r.
\]

In [11]:

Phi = -G*M/r

A_weak = 1 + 2*Phi/c**2
B_weak = 1

g_weak = sp.diag(-A_weak, B_weak, B_weak, B_weak)
Gamma_weak = christoffel_symbols(g_weak, coords)

a_geo = sp.Matrix([
    -c**2 * sp.simplify(Gamma_weak[i][0][0])
    for i in range(1, 4)
])

a_newton = sp.Matrix([
    -sp.diff(Phi, coord)
    for coord in (x, y, z)
])

print("Accélération issue des Christoffel :")
display(sp.simplify(a_geo))

print("Accélération newtonienne :")
display(sp.simplify(a_newton))

difference = sp.simplify(a_geo - a_newton)

print("Différence :")
display(difference)

Accélération issue des Christoffel :

⎡     -G⋅M⋅x      ⎤
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎢⎝x  + y  + z ⎠   ⎥
⎢                 ⎥
⎢     -G⋅M⋅y      ⎥
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎢⎝x  + y  + z ⎠   ⎥
⎢                 ⎥
⎢     -G⋅M⋅z      ⎥
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎣⎝x  + y  + z ⎠   ⎦

Accélération newtonienne :

⎡     -G⋅M⋅x      ⎤
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎢⎝x  + y  + z ⎠   ⎥
⎢                 ⎥
⎢     -G⋅M⋅y      ⎥
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎢⎝x  + y  + z ⎠   ⎥
⎢                 ⎥
⎢     -G⋅M⋅z      ⎥
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎣⎝x  + y  + z ⎠   ⎦

Différence :

⎡0⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣0⎦


## Remarque sur l'ordre d'approximation

Avec

\[
A=1+\frac{2\Phi}{c^2},
\]

le calcul exact de \(-c^2\Gamma^i_{00}\) contient des corrections d'ordre supérieur en \(\Phi/c^2\).

La récupération newtonienne doit donc être comprise au premier ordre :

\[
\left|\frac{\Phi}{c^2}\right|\ll1.
\]

La cellule suivante développe explicitement l'accélération en série perturbative.

In [12]:

lambda_weak = sp.symbols("lambda_weak", real=True)

Phi_scaled = lambda_weak * Phi
A_scaled = 1 + 2*Phi_scaled/c**2
g_scaled = sp.diag(-A_scaled, 1, 1, 1)

Gamma_scaled = christoffel_symbols(g_scaled, coords)

a_scaled = sp.Matrix([
    -c**2 * Gamma_scaled[i][0][0]
    for i in range(1, 4)
])

a_first_order = a_scaled.applyfunc(
    lambda expr: sp.series(expr, lambda_weak, 0, 2).removeO()
)

print("Accélération géodésique au premier ordre :")
display(sp.simplify(a_first_order))

print("Accélération newtonienne multipliée par lambda_weak :")
display(sp.simplify(lambda_weak * a_newton))

print("Différence au premier ordre :")
display(sp.simplify(a_first_order - lambda_weak*a_newton))

Accélération géodésique au premier ordre :

⎡ -G⋅M⋅λ_weak⋅x   ⎤
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎢⎝x  + y  + z ⎠   ⎥
⎢                 ⎥
⎢ -G⋅M⋅λ_weak⋅y   ⎥
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎢⎝x  + y  + z ⎠   ⎥
⎢                 ⎥
⎢ -G⋅M⋅λ_weak⋅z   ⎥
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎣⎝x  + y  + z ⎠   ⎦

Accélération newtonienne multipliée par lambda_weak :

⎡ -G⋅M⋅λ_weak⋅x   ⎤
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎢⎝x  + y  + z ⎠   ⎥
⎢                 ⎥
⎢ -G⋅M⋅λ_weak⋅y   ⎥
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎢⎝x  + y  + z ⎠   ⎥
⎢                 ⎥
⎢ -G⋅M⋅λ_weak⋅z   ⎥
⎢─────────────────⎥
⎢              3/2⎥
⎢⎛ 2    2    2⎞   ⎥
⎣⎝x  + y  + z ⎠   ⎦

Différence au premier ordre :

⎡0⎤
⎢ ⎥
⎢0⎥
⎢ ⎥
⎣0⎦


# 9. Fonction métrique GVH configurable

La fonction suivante centralise plusieurs modèles :

- `flat` : espace plat ;
- `weak_field` : limite newtonienne faible ;
- `schwarzschild_isotropic` : référence relativiste exacte ;
- `gvh_series` : famille exploratoire avec coefficients libres.

La famille exploratoire est définie par :

\[
A_{\mathrm{GVH}}(\chi)
=
1-2\chi+a_2\chi^2+a_3\chi^3,
\]

\[
B_{\mathrm{GVH}}(\chi)
=
1+2\gamma\chi+b_2\chi^2+b_3\chi^3.
\]

Elle ne constitue pas encore une théorie validée.

In [13]:

def gvh_metric_symbolic(model="flat", params=None):
    params = {} if params is None else dict(params)

    if model == "flat":
        A_model = sp.Integer(1)
        B_model = sp.Integer(1)

    elif model == "weak_field":
        A_model = 1 - 2*chi
        B_model = 1 + 2*chi

    elif model == "schwarzschild_isotropic":
        A_model = A_schw
        B_model = B_schw

    elif model == "gvh_series":
        a2 = sp.sympify(params.get("a2", sp.Symbol("a2")))
        a3 = sp.sympify(params.get("a3", sp.Symbol("a3")))
        gamma = sp.sympify(params.get("gamma", sp.Symbol("gamma")))
        b2 = sp.sympify(params.get("b2", sp.Symbol("b2")))
        b3 = sp.sympify(params.get("b3", sp.Symbol("b3")))

        A_model = 1 - 2*chi + a2*chi**2 + a3*chi**3
        B_model = 1 + 2*gamma*chi + b2*chi**2 + b3*chi**3

    else:
        raise ValueError(
            "Modèle inconnu. Utiliser flat, weak_field, "
            "schwarzschild_isotropic ou gvh_series."
        )

    return sp.diag(-sp.simplify(A_model),
                   sp.simplify(B_model),
                   sp.simplify(B_model),
                   sp.simplify(B_model))

g_test = gvh_metric_symbolic("gvh_series")
display(g_test)

⎡         3  3                   2  2                                          ↪
⎢        G ⋅M ⋅a₃               G ⋅M ⋅a₂                 2⋅G⋅M                 ↪
⎢- ──────────────────── - ───────────────────── + ──────────────────── - 1     ↪
⎢                   3/2    4  2    4  2    4  2         ______________         ↪
⎢   6 ⎛ 2    2    2⎞      c ⋅x  + c ⋅y  + c ⋅z     2   ╱  2    2    2          ↪
⎢  c ⋅⎝x  + y  + z ⎠                              c ⋅╲╱  x  + y  + z           ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                    0                                      ── ↪
⎢                                                                              ↪
⎢                                                                            6 ↪
⎢                                                                           c  ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                    0                                         ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎢                                    0                                         ↪
⎢                                                                              ↪
⎢                                                                              ↪
⎣                                                                              ↪

↪                                                                              ↪
↪                                                                              ↪
↪                                  0                                           ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪      3  3                   2  2                                             ↪
↪     G ⋅M ⋅b₃               G ⋅M ⋅b₂                2⋅G⋅M⋅γ                   ↪
↪ ────────────────── + ───────────────────── + ──────────────────── + 1        ↪
↪                3/2    4  2    4  2    4  2         ______________            ↪
↪  ⎛ 2    2    2⎞      c ⋅x  + c ⋅y  + c ⋅z     2   ╱  2    2    2             ↪
↪ ⋅⎝x  + y  + z ⎠                              c ⋅╲╱  x  + y  + z              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                  0                                     ───── ↪
↪                                                                              ↪
↪                                                                         6 ⎛  ↪
↪                                                                        c ⋅⎝x ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                  0                                           ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪

↪                                                                              ↪
↪                                                                              ↪
↪                               0                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                               0                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪   3  3                   2  2                                                ↪
↪  G ⋅M ⋅b₃               G ⋅M ⋅b₂                2⋅G⋅M⋅γ                      ↪
↪ ─────────────── + ───────────────────── + ──────────────────── + 1           ↪
↪             3/2    4  2    4  2    4  2         ______________               ↪
↪ 2    2    2⎞      c ⋅x  + c ⋅y  + c ⋅z     2   ╱  2    2    2                ↪
↪   + y  + z ⎠                              c ⋅╲╱  x  + y  + z                 ↪
↪                                                                              ↪
↪                                                                            3 ↪
↪                                                                           G  ↪
↪                               0                                     ──────── ↪
↪                                                                              ↪
↪                                                                      6 ⎛ 2   ↪
↪                                                                     c ⋅⎝x  + ↪

↪                                                                ⎤
↪                                                                ⎥
↪                            0                                   ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                            0                                   ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                            0                                   ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                                                                ⎥
↪                                                                ⎥
↪   3                   2  2                                     ⎥
↪ ⋅M ⋅b₃               G ⋅M ⋅b₂                2⋅G⋅M⋅γ           ⎥
↪ ──────────── + ───────────────────── + ──────────────────── + 1⎥
↪          3/2    4  2    4  2    4  2         ______________    ⎥
↪   2    2⎞      c ⋅x  + c ⋅y  + c ⋅z     2   ╱  2    2    2     ⎥
↪  y  + z ⎠                              c ⋅╲╱  x  + y  + z      ⎦


# 10. Génération automatique d'un dictionnaire exploitable

Pour le futur intégrateur de géodésiques, il est utile de convertir les symboles de Christoffel en dictionnaire clair :

\[
(\mu,\alpha,\beta)
\longmapsto
\Gamma^\mu_{\alpha\beta}.
\]

Nous ne conservons que les composantes non nulles.

In [14]:

def christoffel_dictionary(Gamma):
    output = {}
    n = len(Gamma)

    for mu in range(n):
        for alpha in range(n):
            for beta in range(n):
                expr = sp.simplify(Gamma[mu][alpha][beta])
                if expr != 0:
                    output[(mu, alpha, beta)] = expr

    return output

Gamma_schw_dict = christoffel_dictionary(Gamma_schw)

print("Nombre d'entrées :", len(Gamma_schw_dict))
list(Gamma_schw_dict.items())[:8]

Nombre d'entrées : 30

⎡                                                                              ↪
⎢⎛                          ⎛              ______________⎞ ⎛                   ↪
⎢⎜                      2   ⎜         2   ╱  2    2    2 ⎟ ⎜ 2  2          2   ↪
⎢⎜              -4⋅G⋅M⋅c ⋅x⋅⎝G⋅M - 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝G ⋅M  + 4⋅G⋅M⋅c ⋅╲ ↪
⎢⎜(0, 0, 1), ───────────────────────────────────────────────────────────────── ↪
⎢⎜                                         3                                   ↪
⎢⎜           ⎛              ______________⎞     ______________ ⎛               ↪
⎢⎜           ⎜         2   ╱  2    2    2 ⎟    ╱  2    2    2  ⎜ 2  2          ↪
⎣⎝           ⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠ ⋅╲╱  x  + y  + z  ⋅⎝G ⋅M  - 4⋅G⋅M⋅ ↪

↪                                                                              ↪
↪   ______________                              ⎞    ⎞  ⎛                      ↪
↪  ╱  2    2    2       4  2      4  2      4  2⎟    ⎟  ⎜                      ↪
↪ ╱  x  + y  + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠    ⎟  ⎜              -4⋅G⋅M⋅ ↪
↪ ───────────────────────────────────────────────────⎟, ⎜(0, 0, 2), ────────── ↪
↪                                                    ⎟  ⎜                      ↪
↪       ______________                              ⎞⎟  ⎜           ⎛          ↪
↪  2   ╱  2    2    2       4  2      4  2      4  2⎟⎟  ⎜           ⎜          ↪
↪ c ⋅╲╱  x  + y  + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠⎠  ⎝           ⎝G⋅M + 2⋅c ↪

↪                                                                              ↪
↪      ⎛              ______________⎞ ⎛                    ______________      ↪
↪  2   ⎜         2   ╱  2    2    2 ⎟ ⎜ 2  2          2   ╱  2    2    2       ↪
↪ c ⋅y⋅⎝G⋅M - 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝G ⋅M  + 4⋅G⋅M⋅c ⋅╲╱  x  + y  + z   + 4⋅ ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                     3                                                        ↪
↪      ______________⎞     ______________ ⎛                    ______________  ↪
↪ 2   ╱  2    2    2 ⎟    ╱  2    2    2  ⎜ 2  2          2   ╱  2    2    2   ↪
↪  ⋅╲╱  x  + y  + z  ⎠ ⋅╲╱  x  + y  + z  ⋅⎝G ⋅M  - 4⋅G⋅M⋅c ⋅╲╱  x  + y  + z    ↪

↪                                                                              ↪
↪                          ⎞    ⎞  ⎛                          ⎛              _ ↪
↪  4  2      4  2      4  2⎟    ⎟  ⎜                      2   ⎜         2   ╱  ↪
↪ c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠    ⎟  ⎜              -4⋅G⋅M⋅c ⋅z⋅⎝G⋅M - 2⋅c ⋅╲╱   ↪
↪ ──────────────────────────────⎟, ⎜(0, 0, 3), ─────────────────────────────── ↪
↪                               ⎟  ⎜                                         3 ↪
↪                              ⎞⎟  ⎜           ⎛              ______________⎞  ↪
↪      4  2      4  2      4  2⎟⎟  ⎜           ⎜         2   ╱  2    2    2 ⎟  ↪
↪ + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠⎠  ⎝           ⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠  ↪

↪                                                                              ↪
↪ _____________⎞ ⎛                    ______________                           ↪
↪  2    2    2 ⎟ ⎜ 2  2          2   ╱  2    2    2       4  2      4  2       ↪
↪ x  + y  + z  ⎠⋅⎝G ⋅M  + 4⋅G⋅M⋅c ⋅╲╱  x  + y  + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                                                              ↪
↪     ______________ ⎛                    ______________                       ↪
↪    ╱  2    2    2  ⎜ 2  2          2   ╱  2    2    2       4  2      4  2   ↪
↪ ⋅╲╱  x  + y  + z  ⋅⎝G ⋅M  - 4⋅G⋅M⋅c ⋅╲╱  x  + y  + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + ↪

↪                                                                              ↪
↪     ⎞    ⎞  ⎛                          ⎛              ______________⎞ ⎛      ↪
↪ 4  2⎟    ⎟  ⎜                      2   ⎜         2   ╱  2    2    2 ⎟ ⎜ 2  2 ↪
↪  ⋅z ⎠    ⎟  ⎜              -4⋅G⋅M⋅c ⋅x⋅⎝G⋅M - 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝G ⋅M  ↪
↪ ─────────⎟, ⎜(0, 1, 0), ──────────────────────────────────────────────────── ↪
↪          ⎟  ⎜                                         3                      ↪
↪         ⎞⎟  ⎜           ⎛              ______________⎞     ______________ ⎛  ↪
↪     4  2⎟⎟  ⎜           ⎜         2   ╱  2    2    2 ⎟    ╱  2    2    2  ⎜  ↪
↪  4⋅c ⋅z ⎠⎠  ⎝           ⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠ ⋅╲╱  x  + y  + z  ⋅⎝G ↪

↪                                                                              ↪
↪                ______________                              ⎞    ⎞  ⎛         ↪
↪           2   ╱  2    2    2       4  2      4  2      4  2⎟    ⎟  ⎜         ↪
↪  + 4⋅G⋅M⋅c ⋅╲╱  x  + y  + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠    ⎟  ⎜         ↪
↪ ────────────────────────────────────────────────────────────────⎟, ⎜(0, 2, 0 ↪
↪                                                                 ⎟  ⎜         ↪
↪                    ______________                              ⎞⎟  ⎜         ↪
↪ 2  2          2   ╱  2    2    2       4  2      4  2      4  2⎟⎟  ⎜         ↪
↪  ⋅M  - 4⋅G⋅M⋅c ⋅╲╱  x  + y  + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠⎠  ⎝         ↪

↪                                                                              ↪
↪                   ⎛              ______________⎞ ⎛                    ______ ↪
↪               2   ⎜         2   ╱  2    2    2 ⎟ ⎜ 2  2          2   ╱  2    ↪
↪       -4⋅G⋅M⋅c ⋅y⋅⎝G⋅M - 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝G ⋅M  + 4⋅G⋅M⋅c ⋅╲╱  x  +  ↪
↪ ), ───────────────────────────────────────────────────────────────────────── ↪
↪                                  3                                           ↪
↪    ⎛              ______________⎞     ______________ ⎛                    __ ↪
↪    ⎜         2   ╱  2    2    2 ⎟    ╱  2    2    2  ⎜ 2  2          2   ╱   ↪
↪    ⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠ ⋅╲╱  x  + y  + z  ⋅⎝G ⋅M  - 4⋅G⋅M⋅c ⋅╲╱  x ↪

↪                                                                              ↪
↪ ________                              ⎞    ⎞  ⎛                          ⎛   ↪
↪  2    2       4  2      4  2      4  2⎟    ⎟  ⎜                      2   ⎜   ↪
↪ y  + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠    ⎟  ⎜              -4⋅G⋅M⋅c ⋅z⋅⎝G⋅ ↪
↪ ───────────────────────────────────────────⎟, ⎜(0, 3, 0), ────────────────── ↪
↪                                            ⎟  ⎜                              ↪
↪ ____________                              ⎞⎟  ⎜           ⎛              ___ ↪
↪ 2    2    2       4  2      4  2      4  2⎟⎟  ⎜           ⎜         2   ╱  2 ↪
↪   + y  + z   + 4⋅c ⋅x  + 4⋅c ⋅y  + 4⋅c ⋅z ⎠⎠  ⎝           ⎝G⋅M + 2⋅c ⋅╲╱  x  ↪

↪                                                                              ↪
↪             ______________⎞ ⎛                    ______________              ↪
↪        2   ╱  2    2    2 ⎟ ⎜ 2  2          2   ╱  2    2    2       4  2    ↪
↪ M - 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝G ⋅M  + 4⋅G⋅M⋅c ⋅╲╱  x  + y  + z   + 4⋅c ⋅x  +  ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪             3                                                                ↪
↪ ___________⎞     ______________ ⎛                    ______________          ↪
↪     2    2 ⎟    ╱  2    2    2  ⎜ 2  2          2   ╱  2    2    2       4   ↪
↪  + y  + z  ⎠ ⋅╲╱  x  + y  + z  ⋅⎝G ⋅M  - 4⋅G⋅M⋅c ⋅╲╱  x  + y  + z   + 4⋅c ⋅x ↪

↪                                                                              ↪
↪                  ⎞    ⎞  ⎛                                                   ↪
↪    4  2      4  2⎟    ⎟  ⎜                                                   ↪
↪ 4⋅c ⋅y  + 4⋅c ⋅z ⎠    ⎟  ⎜                                                   ↪
↪ ──────────────────────⎟, ⎜(1, 0, 0), ─────────────────────────────────────── ↪
↪                       ⎟  ⎜                                         3         ↪
↪                      ⎞⎟  ⎜           ⎛              ______________⎞     ____ ↪
↪ 2      4  2      4  2⎟⎟  ⎜           ⎜         2   ╱  2    2    2 ⎟    ╱  2  ↪
↪   + 4⋅c ⋅y  + 4⋅c ⋅z ⎠⎠  ⎝           ⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠ ⋅╲╱  x   ↪

↪                                                                              ↪
↪                                                                              ↪
↪                                                                              ↪
↪                                                                         -64⋅ ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                                                              ↪
↪ __________ ⎛                      ______________                             ↪
↪    2    2  ⎜ 4  4      3  3  2   ╱  2    2    2        2  2  4  2       2  2 ↪
↪ + y  + z  ⋅⎝G ⋅M  + 8⋅G ⋅M ⋅c ⋅╲╱  x  + y  + z   + 24⋅G ⋅M ⋅c ⋅x  + 24⋅G ⋅M  ↪

↪                                                                              ↪
↪           ⎛              ______________⎞                                     ↪
↪      10   ⎜         2   ╱  2    2    2 ⎟ ⎛ 4      2  2      2  2    4      2 ↪
↪ G⋅M⋅c  ⋅x⋅⎝G⋅M - 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝x  + 2⋅x ⋅y  + 2⋅x ⋅z  + y  + 2⋅y  ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                                                              ↪
↪                                           ______________                   _ ↪
↪   4  2       2  2  4  2           6  2   ╱  2    2    2            6  2   ╱  ↪
↪ ⋅c ⋅y  + 24⋅G ⋅M ⋅c ⋅z  + 32⋅G⋅M⋅c ⋅x ⋅╲╱  x  + y  + z   + 32⋅G⋅M⋅c ⋅y ⋅╲╱   ↪

↪                                                                              ↪
↪                                                                              ↪
↪   2    4⎞                                                                    ↪
↪ ⋅z  + z ⎠                                                                    ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                                                              ↪
↪ _____________                   ______________                               ↪
↪  2    2    2            6  2   ╱  2    2    2        8  4       8  2  2      ↪
↪ x  + y  + z   + 32⋅G⋅M⋅c ⋅z ⋅╲╱  x  + y  + z   + 16⋅c ⋅x  + 32⋅c ⋅x ⋅y  + 32 ↪

↪                                                  ⎛                           ↪
↪                                               ⎞  ⎜                           ↪
↪                                               ⎟  ⎜                           ↪
↪                                               ⎟  ⎜                           ↪
↪ ──────────────────────────────────────────────⎟, ⎜(1, 1, 1), ─────────────── ↪
↪                                               ⎟  ⎜                         1 ↪
↪                                              ⎞⎟  ⎜           ⎛ 2    2    2⎞  ↪
↪   8  2  2       8  4       8  2  2       8  4⎟⎟  ⎝           ⎝x  + y  + z ⎠  ↪
↪ ⋅c ⋅x ⋅z  + 16⋅c ⋅y  + 32⋅c ⋅y ⋅z  + 16⋅c ⋅z ⎠⎠                              ↪

↪                                                                              ↪
↪                                                      ⎛              ________ ↪
↪                                                      ⎜         2   ╱  2    2 ↪
↪                                                  2⋅x⋅⎝G⋅M + 2⋅c ⋅╲╱  x  + y  ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪ 1/2 ⎛                      ______________                                    ↪
↪     ⎜ 4  4      3  3  2   ╱  2    2    2        2  2  4  2       2  2  4  2  ↪
↪    ⋅⎝G ⋅M  + 8⋅G ⋅M ⋅c ⋅╲╱  x  + y  + z   + 24⋅G ⋅M ⋅c ⋅x  + 24⋅G ⋅M ⋅c ⋅y   ↪
↪                                                                              ↪

↪        3                                                                     ↪
↪ ______⎞  ⎛                   3   ⎛              ______________⎞              ↪
↪     2 ⎟  ⎜   2 ⎛ 2    2    2⎞    ⎜         2   ╱  2    2    2 ⎟ ⎛ 2    2     ↪
↪  + z  ⎠ ⋅⎝2⋅c ⋅⎝x  + y  + z ⎠  - ⎝G⋅M + 2⋅c ⋅╲╱  x  + y  + z  ⎠⋅⎝x  + y  + z ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪                                    ______________                   ________ ↪
↪       2  2  4  2           6  2   ╱  2    2    2            6  2   ╱  2    2 ↪
↪ + 24⋅G ⋅M ⋅c ⋅z  + 32⋅G⋅M⋅c ⋅x ⋅╲╱  x  + y  + z   + 32⋅G⋅M⋅c ⋅y ⋅╲╱  x  + y  ↪
↪                                                                              ↪

↪                                                                              ↪
↪   5/2⎞                                                                       ↪
↪ 2⎞   ⎟ ⎛ 4      2  2      2  2    4      2  2    4⎞                          ↪
↪  ⎠   ⎠⋅⎝x  + 2⋅x ⋅y  + 2⋅x ⋅z  + y  + 2⋅y ⋅z  + z ⎠                          ↪
↪ ──────────────────────────────────────────────────────────────────────────── ↪
↪ ______                   ______________                                      ↪
↪     2            6  2   ╱  2    2    2        8  4       8  2  2       8  2  ↪
↪  + z   + 32⋅G⋅M⋅c ⋅z ⋅╲╱  x  + y  + z   + 16⋅c ⋅x  + 32⋅c ⋅x ⋅y  + 32⋅c ⋅x ⋅ ↪
↪                                                                              ↪

↪                                        ⎞⎤
↪                                        ⎟⎥
↪                                        ⎟⎥
↪                                        ⎟⎥
↪ ───────────────────────────────────────⎟⎥
↪                                       ⎞⎟⎥
↪  2       8  4       8  2  2       8  4⎟⎟⎥
↪ z  + 16⋅c ⋅y  + 32⋅c ⋅y ⋅z  + 16⋅c ⋅z ⎠⎠⎥
↪                                         ⎦


# 11. Conversion symbolique vers fonctions numériques

`SymPy.lambdify` permet de transformer les expressions symboliques en fonctions NumPy.

Cette étape est essentielle pour la version suivante :

\[
\texttt{GVH\_Diagonal\_Cubic\_0.2.3\_Geodesic\_Integrator.ipynb}.
\]

Pour réduire le coût numérique, seules les composantes non nulles sont converties.

In [15]:

def lambdify_christoffel_dict(Gamma_dict, parameters=(G, M, c)):
    numerical = {}

    variables = (ct, x, y, z) + tuple(parameters)

    for key, expr in Gamma_dict.items():
        numerical[key] = sp.lambdify(
            variables,
            expr,
            modules="numpy"
        )

    return numerical

Gamma_schw_numeric = lambdify_christoffel_dict(Gamma_schw_dict)

print("Fonctions numériques générées :", len(Gamma_schw_numeric))

Fonctions numériques générées : 30


# 12. Test numérique ponctuel

Nous évaluons quelques symboles de Christoffel autour du Soleil à la distance orbitale moyenne de Mercure.

Ce test ne constitue pas encore une intégration de trajectoire. Il vérifie seulement que :

1. les fonctions numériques s'évaluent correctement ;
2. les résultats sont finis ;
3. les valeurs sont faibles dans le régime solaire.

In [16]:

G_num = 6.67430e-11
M_sun_num = 1.98847e30
c_num = 299_792_458.0
r_mercury = 57.909e9

point = (0.0, r_mercury, 0.0, 0.0, G_num, M_sun_num, c_num)

sample_rows = []

for key, func in list(Gamma_schw_numeric.items())[:12]:
    value = float(np.asarray(func(*point)))
    sample_rows.append({
        "mu": key[0],
        "alpha": key[1],
        "beta": key[2],
        "value": value,
        "finite": np.isfinite(value)
    })

sample_df = pd.DataFrame(sample_rows)
sample_df

    mu  alpha  beta         value  finite
0    0      0     1  4.403431e-19    True
1    0      0     2  0.000000e+00    True
2    0      0     3  0.000000e+00    True
3    0      1     0  4.403431e-19    True
4    0      2     0  0.000000e+00    True
5    0      3     0  0.000000e+00    True
6    1      0     0  4.403431e-19    True
7    1      1     1 -4.403431e-19    True
8    1      1     2 -0.000000e+00    True
9    1      1     3 -0.000000e+00    True
10   1      2     1 -0.000000e+00    True
11   1      2     2  4.403431e-19    True

In [17]:

assert sample_df["finite"].all()
print("Toutes les composantes testées sont finies.")

Toutes les composantes testées sont finies.


# 13. Test de covariance sous rotation — préparation

La métrique spatiale

\[
B(r)\delta_{ij}
\]

est isotrope. Puisque

\[
r^2=x^2+y^2+z^2
\]

est invariant sous rotation, la forme métrique doit être indépendante de l'orientation du cube.

Pour une rotation orthogonale \(R\),

\[
R^\mathsf{T}R=I,
\]

et le bloc spatial se transforme comme

\[
g'_{\mathrm{spatial}}
=
R^\mathsf{T}
\left(BI\right)
R
=
BI.
\]

In [18]:

theta = sp.symbols("theta", real=True)

Rz = sp.Matrix([
    [sp.cos(theta), -sp.sin(theta), 0],
    [sp.sin(theta),  sp.cos(theta), 0],
    [0,              0,             1]
])

g_spatial = B * sp.eye(3)
g_rotated = sp.simplify(Rz.T * g_spatial * Rz)

print("Bloc spatial après rotation :")
display(g_rotated)

print("Différence avec le bloc initial :")
display(sp.simplify(g_rotated - g_spatial))

Bloc spatial après rotation :

⎡ ⎛   ______________⎞                                            ⎤
⎢ ⎜  ╱  2    2    2 ⎟                                            ⎥
⎢B⎝╲╱  x  + y  + z  ⎠           0                     0          ⎥
⎢                                                                ⎥
⎢                       ⎛   ______________⎞                      ⎥
⎢                       ⎜  ╱  2    2    2 ⎟                      ⎥
⎢         0            B⎝╲╱  x  + y  + z  ⎠           0          ⎥
⎢                                                                ⎥
⎢                                             ⎛   ______________⎞⎥
⎢                                             ⎜  ╱  2    2    2 ⎟⎥
⎣         0                     0            B⎝╲╱  x  + y  + z  ⎠⎦

Différence avec le bloc initial :

⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦


# 14. Résumé des validations

| Test | Résultat attendu |
|---|---|
| Inversion métrique | \(g^{\mu\nu}g_{\nu\rho}=\delta^\mu{}_\rho\) |
| Symétrie Christoffel | \(\Gamma^\mu_{\alpha\beta}=\Gamma^\mu_{\beta\alpha}\) |
| Minkowski | tous les \(\Gamma^\mu_{\alpha\beta}=0\) |
| Champ faible | récupération de \(-\nabla\Phi\) au premier ordre |
| Schwarzschild isotrope | connexions non nulles générées automatiquement |
| Rotation | invariance du bloc spatial isotrope |

La réussite de ces tests valide l'infrastructure mathématique, mais pas encore une métrique nouvelle propre à GVH.

In [19]:

validation_summary = pd.DataFrame([
    {
        "test": "Symétrie indices inférieurs",
        "statut": "PASS" if len(symmetry_failures) == 0 else "FAIL"
    },
    {
        "test": "Minkowski sans connexion",
        "statut": "PASS" if len(nonzero_minkowski) == 0 else "FAIL"
    },
    {
        "test": "Évaluation numérique finie",
        "statut": "PASS" if sample_df["finite"].all() else "FAIL"
    },
    {
        "test": "Invariance rotation bloc spatial",
        "statut": "PASS" if sp.simplify(g_rotated-g_spatial) == sp.zeros(3) else "FAIL"
    }
])

validation_summary

                               test statut
0       Symétrie indices inférieurs   PASS
1          Minkowski sans connexion   PASS
2        Évaluation numérique finie   PASS
3  Invariance rotation bloc spatial   PASS


# 15. Conclusion

Cette version établit un calcul automatique et réutilisable des symboles de Christoffel pour toute métrique diagonale cubique de type

\[
g_{\mu\nu}
=
\operatorname{diag}
\left[-A(r),B(r),B(r),B(r)\right].
\]

Les points acquis sont :

1. construction symbolique de \(g_{\mu\nu}\) et \(g^{\mu\nu}\) ;
2. calcul automatique de \(\Gamma^\mu_{\alpha\beta}\) ;
3. extraction des composantes non nulles ;
4. vérification de la symétrie des indices inférieurs ;
5. validation sur Minkowski ;
6. application à Schwarzschild isotrope ;
7. récupération de Newton au premier ordre faible ;
8. conversion vers des fonctions numériques ;
9. préparation du test de covariance sous rotation.

---

## Étape suivante

\[
\boxed{
\texttt{GVH\_Diagonal\_Cubic\_0.2.3\_Geodesic\_Integrator.ipynb}
}
\]

Cette prochaine version devra intégrer :

\[
\frac{d^2X^\mu}{d\lambda^2}
+
\Gamma^\mu_{\alpha\beta}
\frac{dX^\alpha}{d\lambda}
\frac{dX^\beta}{d\lambda}
=
0,
\]

puis comparer les trajectoires obtenues avec :

- mouvement rectiligne dans Minkowski ;
- limite orbitale newtonienne ;
- géodésiques de Schwarzschild ;
- tests de rotation des axes.